<?php

namespace Persi\CatalogEngine\Attributes;

defined( 'ABSPATH' ) || exit;

final class AttributeStatuses {
	public const DISCOVERED = 'ATTRIBUTE_DISCOVERED';
	public const CANDIDATE = 'ATTRIBUTE_CANDIDATE';
	public const WOULD_UPDATE = 'ATTRIBUTE_WOULD_UPDATE';
	public const ALREADY_SYNCED = 'ATTRIBUTE_ALREADY_SYNCED';
	public const CONFLICT = 'ATTRIBUTE_CONFLICT';
	public const MAPPING_REQUIRED = 'ATTRIBUTE_MAPPING_REQUIRED';
	public const REVIEW_REQUIRED = 'ATTRIBUTE_REVIEW_REQUIRED';
	public const INVALID_VALUE = 'ATTRIBUTE_INVALID_VALUE';
	public const SKIPPED = 'ATTRIBUTE_SKIPPED';
	public const NO_VALUE = 'ATTRIBUTE_NO_VALUE';
	public const UNSUPPORTED_CONTEXT = 'ATTRIBUTE_UNSUPPORTED_CONTEXT';
	public const TERM_MATCHED = 'ATTRIBUTE_TERM_MATCHED';
	public const TERM_MAPPING_REQUIRED = 'ATTRIBUTE_TERM_MAPPING_REQUIRED';
	public const UNIT_AMBIGUOUS = 'ATTRIBUTE_UNIT_AMBIGUOUS';
	public const CONCEPT_AMBIGUOUS = 'ATTRIBUTE_CONCEPT_AMBIGUOUS';
	public const SOURCE_CONFLICT = 'ATTRIBUTE_SOURCE_CONFLICT';
	public const UNSUPPORTED_UNIT = 'ATTRIBUTE_UNSUPPORTED_UNIT';
	public const DESTINATION_MISSING = 'ATTRIBUTE_DESTINATION_MISSING';
	public const UPDATED = 'ATTRIBUTE_UPDATED';
	public const ERROR = 'ATTRIBUTE_ERROR';
}
