import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";

import { PimEditorialEditor } from "@/components/admin/PimEditorialEditor";
import { getPimProduct } from "@/lib/pim/repository";
import { reviewSuggestion } from "./actions";

function money(amount:string|null,currency:string|null){if(!amount)return "—";return new Intl.NumberFormat("pt-BR",{style:"currency",currency:currency??"BRL"}).format(Number(amount)/100);}
function label(value:string){return value.replaceAll("_"," ");}

export default async function PimProductPage({params}:{params:Promise<{id:string}>}){
  const {id}=await params;const product=await getPimProduct(id).catch(()=>null);if(!product)notFound();
  const source={commercialName:product.name,shortDescription:product.sourceShortDescription,description:product.sourceDescription,bulletPoints:[],application:null,specifications:null,seoTitle:null,metaDescription:null,searchTerms:[],imageAltText:null};
  return <div>
    <Link href="/admin/products" className="text-sm font-semibold text-[#0c2d72] hover:underline">← Voltar aos produtos</Link>
    <div className="mt-4 flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-wide text-[#ff6a00]">Produto / {product.sku}</p><h1 className="max-w-4xl text-2xl font-bold text-[#071f5c]">{product.name}</h1></div><span className="rounded-full bg-blue-100 px-3 py-1 text-sm font-semibold text-blue-800">{label(product.status)}</span></div>
    <nav aria-label="Seções do produto" className="mt-5 flex gap-4 overflow-x-auto border-b text-sm font-semibold text-slate-600">{["Visão geral","Conteúdo","Atributos","SEO","Mídia","Origem","Histórico"].map((item,index)=><a key={item} href={`#section-${index}`} className="whitespace-nowrap border-b-2 border-transparent px-1 py-3 hover:border-[#ff6a00]">{item}</a>)}</nav>

    <section id="section-0" className="mt-6 grid gap-5 rounded-xl border bg-white p-5 lg:grid-cols-[180px_1fr]"><Image src={product.imageUrl??"/images/placeholders/product-placeholder.svg"} alt={product.name} width={180} height={180} unoptimized className="aspect-square w-full rounded-xl border object-contain"/><dl className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Nome atual",product.name],["SKU",product.sku],["GTIN",product.gtin??"Sem GTIN"],["Marca",product.brand??"—"],["Categoria",product.category??"—"],["Preço",money(product.priceMinor,product.currency)],["Promoção",money(product.salePriceMinor,product.currency)],["Estoque",product.stock??"—"],["Origem",product.source],["Última sincronização",product.lastSyncedAt?new Date(product.lastSyncedAt).toLocaleString("pt-BR"):"—"]].map(([term,description])=><div key={term}><dt className="text-xs font-semibold uppercase text-slate-500">{term}</dt><dd className="mt-1 font-medium">{description}</dd>{["Preço","Promoção","Estoque","SKU","GTIN"].includes(term)&&<span className="text-xs text-slate-500">somente leitura</span>}</div>)}</dl></section>

    <section id="section-1" className="mt-6 rounded-xl border bg-white p-5"><h2 className="text-lg font-bold text-[#071f5c]">Conteúdo editorial</h2><p className="mt-1 text-sm text-slate-600">A origem permanece imutável. Somente o rascunho pode ser editado; o aprovado muda apenas por revisão humana.</p><PimEditorialEditor productId={product.id} version={product.version} status={product.status} source={source} draft={product.draft} approved={product.approved}/>{product.suggestions.length>0&&<div className="mt-5 border-t pt-4"><h3 className="font-semibold">SUGGESTED — exige revisão humana</h3>{product.suggestions.map(s=><article key={s.id} className="mt-3 rounded-xl border p-3"><p className="text-xs uppercase text-slate-500">{s.fieldName} · {s.source} · confiança {s.confidence??"—"}</p><p className="my-2 text-sm">{s.value}</p>{s.status==="needs_review"&&<form action={reviewSuggestion} className="flex gap-2"><input type="hidden" name="suggestionId" value={s.id}/><button name="decision" value="approved" className="rounded-xl bg-emerald-700 px-3 py-2 text-sm font-semibold text-white">Aprovar</button><button name="decision" value="rejected" className="rounded-xl border border-red-300 px-3 py-2 text-sm font-semibold text-red-700">Rejeitar</button></form>}</article>)}</div>}</section>

    <section id="section-2" className="mt-6 rounded-xl border bg-white"><div className="border-b p-5"><h2 className="text-lg font-bold text-[#071f5c]">Atributos PIM</h2><p className="text-sm text-slate-600">Somente leitura nesta fase. O valor comercial composto permanece íntegro.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50"><tr>{["Atributo","Valor","Origem","Status","Confiança"].map(x=><th key={x} className="px-5 py-3">{x}</th>)}</tr></thead><tbody className="divide-y">{product.attributes.map(attribute=><tr key={attribute.id}><td className="px-5 py-3 font-semibold">{attribute.name}</td><td className="px-5 py-3">{attribute.value}</td><td className="px-5 py-3">{attribute.source}</td><td className="px-5 py-3">{label(attribute.status)}</td><td className="px-5 py-3">{attribute.confidence??"—"}</td></tr>)}</tbody></table>{product.attributes.length===0&&<p className="p-8 text-center text-slate-500">Nenhum atributo PIM atribuído.</p>}</div></section>

    <section id="section-3" className="mt-6 rounded-xl border bg-white p-5"><h2 className="text-lg font-bold text-[#071f5c]">SEO</h2><p className="mt-2 text-sm text-slate-600">SEO title, meta description e termos de busca são editados no draft. Slug, canonical e URL pública permanecem inalterados.</p><p className="mt-3 text-sm"><strong>Slug atual:</strong> {product.slug}</p></section>
    <section id="section-4" className="mt-6 rounded-xl border bg-white p-5"><h2 className="text-lg font-bold text-[#071f5c]">Mídia</h2><p className="mt-2 text-sm text-slate-600">URLs permanecem no catálogo; nenhum binário é copiado. Apenas o alt editorial possui draft.</p>{product.imageUrl&&<code className="mt-3 block overflow-x-auto rounded bg-slate-100 p-3 text-xs">{product.imageUrl}</code>}</section>
    <section id="section-5" className="mt-6 rounded-xl border bg-white p-5"><h2 className="text-lg font-bold text-[#071f5c]">Origem e segurança</h2><p className="mt-2 text-sm text-slate-600">SKU, GTIN, preço, estoque, reservas e mappings permanecem operacionais e somente leitura.</p></section>
    <section id="section-6" className="mt-6 rounded-xl border bg-white p-5"><h2 className="text-lg font-bold text-[#071f5c]">Histórico</h2>{product.history.length===0?<p className="mt-2 text-sm text-slate-600">Nenhum evento editorial registrado.</p>:<ol className="mt-4 divide-y">{product.history.map(event=><li key={event.id} className="py-3"><p className="font-semibold">{label(event.operation)}</p><p className="text-sm text-slate-600">{new Date(event.createdAt).toLocaleString("pt-BR")} · {event.actorReference}</p>{event.reason&&<p className="mt-1 text-sm">{event.reason}</p>}</li>)}</ol>}</section>
  </div>;
}
