import Image from "next/image";
import Link from "next/link";
import {notFound} from "next/navigation";
import {PimEditorialEditor} from "@/components/admin/PimEditorialEditor";
import {getPimProduct,type PimEditorialContent,type PimSuggestionItem} from "@/lib/pim/repository";
import {reviewSuggestion} from "./actions";

const labels:Record<string,string>={commercial_name:"Nome comercial",short_description:"Descrição curta",description:"Descrição",application:"Aplicação",seo_title:"Título de SEO",meta_description:"Meta description"};
const statusLabel=(value:string)=>({raw:"Sem edição",draft:"Rascunho",needs_review:"Em revisão",approved:"Aprovado no PIM",rejected:"Rejeitado",needs_enrichment:"Precisa revisão"}[value]??value.replaceAll("_"," "));
function currentValue(suggestion:PimSuggestionItem,source:Partial<PimEditorialContent>,draft:PimEditorialContent){const key={commercial_name:"commercialName",short_description:"shortDescription",description:"description",application:"application",seo_title:"seoTitle",meta_description:"metaDescription"}[suggestion.fieldName] as keyof PimEditorialContent|undefined;if(!key)return null;const draftValue=draft[key],sourceValue=source[key];return typeof draftValue==="string"&&draftValue?draftValue:typeof sourceValue==="string"?sourceValue:null;}
function Evidence({suggestion}:{suggestion:PimSuggestionItem}){return <details className="mt-3 rounded-lg bg-background-soft p-3"><summary className="cursor-pointer text-sm font-semibold text-link">Ver evidências e detalhes técnicos</summary>{suggestion.evidenceReferences.length?<ul className="mt-3 space-y-2 text-sm">{suggestion.evidenceReferences.map((e,index)=><li key={`${suggestion.id}-${index}`}><strong>{e.sourceType??"Fonte"}:</strong> {e.rawValue??e.value??e.sourceReference??"Evidência vinculada"}</li>)}</ul>:<p className="mt-3 text-sm text-muted">A sugestão foi validada contra a fonte, mas não possui trecho técnico específico vinculado a este campo editorial.</p>}<dl className="mt-3 grid gap-2 text-xs text-muted sm:grid-cols-2"><div><dt className="font-semibold">Origem</dt><dd>Sugestão automática · {suggestion.provider}/{suggestion.modelVersion}</dd></div><div><dt className="font-semibold">Versão do prompt</dt><dd>{suggestion.promptVersion}</dd></div></dl></details>;}

export default async function PimProductPage({params}:{params:Promise<{id:string}>}){
 const {id}=await params,product=await getPimProduct(id).catch(()=>null);if(!product)notFound();
 const source:Partial<PimEditorialContent>={commercialName:product.name,shortDescription:product.sourceShortDescription,description:product.sourceDescription,application:null,seoTitle:null,metaDescription:null};
 const activeSuggestions=product.suggestions.filter(item=>!item.supersededAt),pending=activeSuggestions.filter(item=>item.status==="needs_review");
 return <div><Link href="/admin/pim" className="text-sm font-semibold text-link hover:underline">← Voltar à fila</Link>
  <header className="mt-4 flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-wide text-secondary">Produto · {product.sku}</p><h1 className="max-w-4xl text-2xl font-bold text-heading">{product.name}</h1><p className="mt-1 text-sm text-muted">{product.brand??"Sem marca"} · {product.category??"Sem categoria"}{product.categoryIsFallback?" (associação secundária)":""}</p></div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-blue-100 px-3 py-1 text-sm font-semibold text-blue-800">{statusLabel(product.status)}</span>{product.hasConflict&&<span className="rounded-full bg-amber-100 px-3 py-1 text-sm font-semibold text-amber-900">Revisão necessária</span>}{!product.imageUrl&&<span className="rounded-full bg-amber-100 px-3 py-1 text-sm font-semibold text-amber-900">Sem imagem</span>}</div></header>
  <nav aria-label="Seções do produto" className="mt-5 flex gap-4 overflow-x-auto border-b text-sm font-semibold text-muted">{[["overview","Visão geral"],["source","Dados de origem"],["suggestions","Sugestões"],["draft","Draft"],["attributes","Atributos"],["media","Mídia"],["audit","Auditoria"]].map(([id,label])=><a key={id} href={`#${id}`} className="whitespace-nowrap border-b-2 border-transparent px-1 py-3 hover:border-secondary">{label}</a>)}</nav>
  <section id="overview" className="mt-6 grid gap-5 rounded-lg border bg-surface p-5 lg:grid-cols-[180px_1fr]"><Image src={product.imageUrl??"/images/placeholders/product-placeholder.svg"} alt={product.imageUrl?product.name:""} width={180} height={180} unoptimized className="aspect-square w-full rounded-lg border object-contain"/><dl className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Nome atual",product.name],["SKU",product.sku],["GTIN",product.gtin??"Sem GTIN"],["Marca",product.brand??"—"],["Categoria",product.category??"Sem categoria"],["Status PIM",statusLabel(product.status)],["Sugestões pendentes",String(product.pendingCount)],["Origem",product.source]].map(([term,value])=><div key={term}><dt className="text-xs font-semibold uppercase text-muted">{term}</dt><dd className="mt-1 font-medium">{value}</dd></div>)}</dl></section>
  <section id="source" className="mt-6 rounded-lg border bg-surface p-5"><h2 className="text-lg font-bold text-heading">Dados de origem</h2><p className="mt-1 text-sm text-muted">Dados do catálogo são somente leitura nesta ferramenta.</p><dl className="mt-4 grid gap-4 lg:grid-cols-2"><div><dt className="font-semibold">Nome atual</dt><dd>{product.name}</dd></div><div><dt className="font-semibold">Descrição curta atual</dt><dd className="whitespace-pre-wrap">{product.sourceShortDescription??"Não informada"}</dd></div><div className="lg:col-span-2"><dt className="font-semibold">Descrição atual</dt><dd className="whitespace-pre-wrap">{product.sourceDescription??"Não informada"}</dd></div></dl></section>
  <section id="suggestions" className="mt-6 rounded-lg border bg-surface p-5"><div className="flex flex-wrap items-end justify-between gap-2"><div><h2 className="text-lg font-bold text-heading">Sugestões PIM</h2><p className="text-sm text-muted">Compare o conteúdo atual com o sugerido e decida individualmente.</p></div><span className="font-semibold text-primary">{pending.length} aguardando revisão</span></div><div className="mt-4 space-y-4">{activeSuggestions.map(suggestion=><article key={suggestion.id} className="rounded-lg border p-4"><div className="flex flex-wrap items-start justify-between gap-2"><h3 className="font-semibold text-heading">{labels[suggestion.fieldName]??suggestion.fieldName}</h3><span className="rounded-full bg-blue-50 px-2 py-1 text-xs font-semibold text-blue-800">{statusLabel(suggestion.status)}</span></div><div className="mt-3 grid gap-3 md:grid-cols-2"><div className="rounded-lg bg-background-soft p-3"><p className="text-xs font-semibold uppercase text-muted">Atual</p><p className="mt-1 whitespace-pre-wrap text-sm">{currentValue(suggestion,source,product.draft)??"Não informado"}</p></div><div className="rounded-lg border border-blue-200 bg-blue-50 p-3"><p className="text-xs font-semibold uppercase text-primary">Sugerido</p><p className="mt-1 whitespace-pre-wrap text-sm">{suggestion.value}</p></div></div><Evidence suggestion={suggestion}/>{suggestion.status==="needs_review"&&<form action={reviewSuggestion} className="mt-4 flex flex-wrap gap-2"><input type="hidden" name="suggestionId" value={suggestion.id}/><button name="decision" value="approved" className="min-h-11 rounded-lg bg-emerald-700 px-4 text-sm font-semibold text-white">Aceitar no draft</button><button name="decision" value="rejected" className="min-h-11 rounded-lg border border-red-300 px-4 text-sm font-semibold text-red-700">Rejeitar</button><a href="#draft" className="inline-flex min-h-11 items-center rounded-lg border px-4 text-sm font-semibold text-link">Editar draft</a></form>}</article>)}{activeSuggestions.length===0&&<p className="rounded-lg bg-background-soft p-6 text-center text-muted">Este produto ainda não possui sugestão automática. Ele continua disponível para revisão manual.</p>}</div></section>
  <section id="draft" className="mt-6 rounded-lg border bg-surface p-5"><h2 className="text-lg font-bold text-heading">Conteúdo editorial</h2><p className="mt-1 text-sm text-muted">Somente os seis campos liberados podem ser editados. Aprovado no PIM não significa publicado no site.</p><PimEditorialEditor productId={product.id} version={product.version} status={product.status} source={source} draft={product.draft} approved={product.approved}/></section>
  <section id="attributes" className="mt-6 rounded-lg border bg-surface p-5"><h2 className="text-lg font-bold text-heading">Atributos e conflitos</h2>{product.hasConflict&&<p className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-950">Há conflito entre fontes. Nenhum vencedor será selecionado automaticamente.</p>}{product.conflicts.length>0&&<div className="mt-4 space-y-3">{product.conflicts.map(conflict=><article key={conflict.id} className="rounded-lg border border-amber-200 bg-amber-50 p-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold text-amber-950">{conflict.attributeKey}</h3><span className="rounded-full bg-amber-200 px-2 py-1 text-xs font-semibold text-amber-950">Conflito aberto</span></div><p className="mt-1 text-sm text-amber-950">{conflict.conflictType.replaceAll("_"," ")} · detector {conflict.detectorVersion}</p>{conflict.metadata.values?.length?<ul className="mt-3 list-disc pl-5 text-sm">{conflict.metadata.values.map(value=><li key={value}>{value}</li>)}</ul>:null}{conflict.metadata.evidence?.length?<details className="mt-3 text-sm"><summary className="cursor-pointer font-semibold">Ver evidências das fontes</summary><ul className="mt-2 space-y-2">{conflict.metadata.evidence.map((item,index)=><li key={`${item.sourceType}-${item.sourceReference}-${index}`} className="rounded bg-white p-2"><strong>{item.sourceType}</strong> · {item.sourceReference}<br/>{item.rawValue}</li>)}</ul></details>:null}</article>)}</div>}<div className="mt-4 overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><thead><tr>{["Atributo","Valor","Origem","Status"].map(item=><th key={item} className="border-b px-3 py-2">{item}</th>)}</tr></thead><tbody>{product.attributes.map(item=><tr key={item.id}><td className="border-b px-3 py-2 font-semibold">{item.name}</td><td className="border-b px-3 py-2">{item.value}</td><td className="border-b px-3 py-2">{item.source}</td><td className="border-b px-3 py-2">{statusLabel(item.status)}</td></tr>)}</tbody></table>{product.attributes.length===0&&<p className="p-6 text-center text-muted">Nenhum atributo cadastrado.</p>}</div></section>
  <section id="media" className="mt-6 rounded-lg border bg-surface p-5"><h2 className="text-lg font-bold text-heading">Mídia</h2><p className="mt-1 text-sm text-muted">Imagens existentes do WordPress. Nenhum arquivo é migrado ou alterado aqui.</p>{product.media.length?<div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{product.media.map(item=><figure key={item.id}><Image src={item.url} alt={item.altText??""} width={180} height={180} unoptimized className="aspect-square w-full rounded-lg border object-contain"/><figcaption className="mt-1 text-xs text-muted">{item.role}</figcaption></figure>)}</div>:<div className="mt-4 rounded-lg bg-background-soft p-8 text-center"><p className="font-semibold">Sem imagem</p><p className="text-sm text-muted">Use o placeholder até a mídia ser cadastrada na origem.</p></div>}</section>
  <section id="audit" className="mt-6 rounded-lg border bg-surface p-5"><h2 className="text-lg font-bold text-heading">Auditoria</h2>{product.history.length?<ol className="mt-4 divide-y">{product.history.map(event=><li key={event.id} className="py-3"><p className="font-semibold">{statusLabel(event.operation)}</p><p className="text-sm text-muted">{new Date(event.createdAt).toLocaleString("pt-BR")} · {event.actorReference}</p>{event.reason&&<p className="mt-1 text-sm">{event.reason}</p>}</li>)}</ol>:<p className="mt-2 text-sm text-muted">Nenhuma ação editorial registrada.</p>}</section>
 </div>;
}
