import assert from "node:assert/strict";
import test from "node:test";
import { compareCatalogProducts, highestSeverity } from "../lib/catalog/comparison.ts";
import { getCatalogFeatureFlags, shouldSampleShadow } from "../lib/catalog/flags.ts";
import { officialReadWithShadow } from "../lib/catalog/shadowCore.ts";
import { mapPostgresProductRow } from "../lib/catalog/postgresMapper.ts";
import { mapWooProductToCatalog } from "../services/catalog/woocommerce.ts";

const product=(overrides={})=>({source:"woocommerce",externalId:1,internalId:null,slug:"produto",name:"Produto",sku:"SKU-1",gtin:null,status:"active",shortDescription:"Curta",description:"Descrição",publishedAt:null,price:{currency:"BRL",regularMinor:1990n,saleMinor:null,saleValidFrom:null,saleValidTo:null},inventory:{quantityAvailable:1n,status:"in-stock"},brand:{externalId:2,name:"Marca",slug:"marca"},categories:[{externalId:3,name:"Categoria",slug:"categoria"}],images:[{externalId:4,url:"https://cdn.test/a.jpg",alt:"",title:null,role:"primary",position:0}],attributes:[{code:"cor",name:"Cor",value:"Preto"}],...overrides});

test("feature flags são Woo/OFF/zero por padrão",()=>{assert.deepEqual(getCatalogFeatureFlags({}),{dataSource:"woocommerce",shadowEnabled:false,shadowSampleRate:0,shadowTimeoutMs:500,canaryPercent:0,postgresTimeoutMs:750});assert.equal(shouldSampleShadow(getCatalogFeatureFlags({}),()=>0),false);});
test("feature flags exigem ativação explícita e limitam sampling",()=>{const flags=getCatalogFeatureFlags({CATALOG_DATA_SOURCE:"postgres",CATALOG_SHADOW_READ_ENABLED:"true",CATALOG_SHADOW_SAMPLE_RATE:"2",CATALOG_SHADOW_TIMEOUT_MS:"9999",CATALOG_CANARY_PERCENT:"150",CATALOG_POSTGRES_TIMEOUT_MS:"9999"});assert.deepEqual(flags,{dataSource:"postgres",shadowEnabled:true,shadowSampleRate:1,shadowTimeoutMs:2000,canaryPercent:100,postgresTimeoutMs:5000});assert.equal(shouldSampleShadow(flags,()=>0.5),true);});
test("comparação normaliza ordem e preserva diferenças comerciais",()=>{const official=product(),shadow=product({source:"postgres",categories:[...officialCategories()].reverse()});assert.equal(compareCatalogProducts(official,shadow).length,0);const differences=compareCatalogProducts(official,product({source:"postgres",price:{...official.price,regularMinor:2000n}}));assert.equal(highestSeverity(differences),"critical");assert.deepEqual(differences.map((item)=>item.field),["price.regularMinor"]);});
test("shadow failure nunca altera resposta oficial",async()=>{const official=product(),events=[];const answer=await officialReadWithShadow("product_by_slug","produto",{official:async()=>official,shadow:async()=>{throw new Error("down");},log:(event)=>events.push(event),random:()=>0,flags:{dataSource:"woocommerce",shadowEnabled:true,shadowSampleRate:1,shadowTimeoutMs:100}});assert.equal(answer,official);await new Promise((resolve)=>setTimeout(resolve,10));assert.equal(events[0].error,"postgres");});
test("shadow timeout não bloqueia resposta Woo",async()=>{const official=product(),events=[],started=performance.now();const answer=await officialReadWithShadow("product_by_slug","produto",{official:async()=>official,shadow:()=>new Promise(()=>{}),log:(event)=>events.push(event),random:()=>0,flags:{dataSource:"woocommerce",shadowEnabled:true,shadowSampleRate:1,shadowTimeoutMs:50}});assert.equal(answer,official);assert.ok(performance.now()-started<40);await new Promise((resolve)=>setTimeout(resolve,70));assert.equal(events[0].error,"timeout");});
test("PostgreSQL adapter preserva bigint, mapping e aggregate",()=>{const mapped=mapPostgresProductRow({externalId:1,internalId:"uuid",slug:"produto",name:"Produto",sku:"SKU-1",gtin:null,status:"active",shortDescription:"Curta",description:"Descrição",publishedAt:null,currency:"BRL",regularMinor:"1990",saleMinor:null,saleValidFrom:null,saleValidTo:null,quantityAvailable:"2",brand:{externalId:2,name:"Marca",slug:"marca"},categories:[{externalId:3,name:"Categoria",slug:"categoria"}],images:[],attributes:[]});assert.equal(mapped.price.regularMinor,1990n);assert.equal(mapped.inventory.status,"in-stock");assert.equal(mapped.externalId,1);});
test("Woo adapter produz o mesmo DTO monetário",()=>{const woo={id:1,slug:"produto",name:"Produto",permalink:"/produto",sku:"SKU-1",shortDescription:"Curta",description:"Descrição",price:19.9,regularPrice:19.9,currencyCode:"BRL",currencySymbol:"R$",currencyMinorUnit:2,images:[],categories:[],brands:[],available:true,stockStatus:"in-stock",averageRating:0,reviewCount:0,featured:false,onSale:false,attributes:[],variations:[]};assert.equal(mapWooProductToCatalog(woo).price.regularMinor,1990n);});

function officialCategories(){return[{externalId:3,name:"Categoria",slug:"categoria"}];}
