import test from "node:test";
import assert from "node:assert/strict";
import {createHash} from "node:crypto";
import {readFileSync} from "node:fs";
import {classifyCompatibilityStatement} from "../lib/pim/compatibility-policy.ts";
import {auditCompactEvidenceBindings,buildPimEvidenceCatalog,resolveCompactEvidence} from "../lib/pim/evidence-catalog.ts";

const output=(attribute,value,ref)=>({suggestedName:null,shortDescription:null,longDescription:null,bulletPoints:[],application:null,attributes:[{attribute,value,evidenceRefs:[ref]}],seo:{title:null,metaDescription:null,searchTerms:[]},uncertainties:[]});
const candidate=(attribute,value,unit=null)=>({attribute,value,rawValue:value,unit,confidence:.9,confidenceBand:"HIGH",status:"CANDIDATE",evidence:[{sourceType:"SOURCE_DESCRIPTION",sourceReference:"description",rawValue:value,normalizedValue:value,confidence:.9,extractionMethod:"deterministic"}],conflictingValues:[]});

test("compatibility classifier distingue aplicação, suporte, claim e ambiguidade",()=>{assert.equal(classifyCompatibilityStatement("Indicado para instalações hidráulicas.",["Categoria hidráulica"]).classification,"GENERIC_APPLICATION_LANGUAGE");assert.equal(classifyCompatibilityStatement("Para uso em instalações elétricas.",["Produto elétrico"]).decision,"PASS");assert.equal(classifyCompatibilityStatement("Compatível com sistema PEX.",["Conexão para sistema PEX"]).classification,"SOURCE_SUPPORTED_COMPATIBILITY");assert.equal(classifyCompatibilityStatement("Compatível com modelo ABC.",["Produto modelo XYZ"]).decision,"BLOCK");assert.equal(classifyCompatibilityStatement("Serve no equipamento XYZ.",["Aplicação geral"]).decision,"BLOCK");assert.equal(classifyCompatibilityStatement("Aplicação em caixa d'água.",["Adaptador para caixa d'água"]).decision,"PASS");assert.equal(classifyCompatibilityStatement("Pode ser usado com qualquer sistema.",["Uso hidráulico"]).classification,"UNSUPPORTED_COMPATIBILITY_CLAIM");assert.equal(classifyCompatibilityStatement("Compatível para uso profissional.",["Uso profissional"]).classification,"AMBIGUOUS_COMPATIBILITY");});

test("evidence ownership, value, unit e compound são fail-safe",()=>{const catalog=buildPimEvidenceCatalog([candidate("voltage","127V","V")],{productReference:"product-a"});assert.doesNotThrow(()=>resolveCompactEvidence(output("voltage","127V","e1"),catalog,{expectedProductReference:"product-a"}));assert.equal(auditCompactEvidenceBindings(output("voltage","127V","e9"),catalog)[0].code,"INVALID_EVIDENCE_REF");assert.equal(auditCompactEvidenceBindings(output("voltage","127V","e1"),catalog,{expectedProductReference:"product-b"})[0].code,"CROSS_PRODUCT_FOREIGN_REF");assert.equal(auditCompactEvidenceBindings(output("current","127V","e1"),catalog)[0].code,"SAME_PRODUCT_SEMANTICALLY_FOREIGN_REF");assert.equal(auditCompactEvidenceBindings(output("voltage","220V","e1"),catalog)[0].code,"UNSUPPORTED_EVIDENCE_VALUE");assert.equal(auditCompactEvidenceBindings(output("voltage","127V/220V","e1"),catalog)[0].code,"UNSUPPORTED_VALUE_EXPANSION");const current=buildPimEvidenceCatalog([candidate("current","10A","A")]);assert.equal(auditCompactEvidenceBindings(output("current","10A/20A","e1"),current)[0].code,"UNSUPPORTED_VALUE_EXPANSION");const power=buildPimEvidenceCatalog([candidate("power","9W","W")]);assert.equal(auditCompactEvidenceBindings(output("power","9W/12W","e1"),power)[0].code,"UNSUPPORTED_VALUE_EXPANSION");const compound=buildPimEvidenceCatalog([candidate("bitola","25mm x 3/4\"","mm")]);assert.equal(auditCompactEvidenceBindings(output("voltage","25mm x 3/4\"","e1"),compound)[0].code,"SAME_PRODUCT_SEMANTICALLY_FOREIGN_REF");});

test("artefatos e outputs históricos P5-B permanecem imutáveis",()=>{const fixture=JSON.parse(readFileSync("tests/fixtures/pim-p5b-historical-outputs.json","utf8")),digest=value=>createHash("sha256").update(value).digest("hex"),resultsText=readFileSync(fixture.sourceArtifacts.results),diagnosticText=readFileSync(fixture.sourceArtifacts.product4Diagnostic),results=JSON.parse(resultsText),diagnostic=JSON.parse(diagnosticText);assert.equal(digest(resultsText),fixture.sourceArtifacts.resultsSha256);assert.equal(digest(diagnosticText),fixture.sourceArtifacts.product4DiagnosticSha256);for(const expected of fixture.outputs){const parsed=expected.product===4?JSON.parse(diagnostic.rawOutputText):results.results.find(item=>item.batchIndex===expected.product).compactModelOutput;assert.equal(digest(JSON.stringify(parsed)),expected.parsedSha256);}});
