import assert from "node:assert/strict";
import {existsSync,readFileSync} from "node:fs";
import test from "node:test";

const resultPath="supabase/.temp/pim-ai/p6b-r1/persistence-result.json";

test("P6-B-R1 persiste somente o manifesto exato",()=>{if(!existsSync(resultPath))return;const value=JSON.parse(readFileSync(resultPath,"utf8"));assert.equal(value.state,"COMPLETED");assert.equal(value.manifest.hashMatch,true);assert.equal(value.manifest.products,387);assert.equal(value.transaction.inserted,2322);assert.equal(value.manifestVerification.persisted,2322);assert.equal(value.manifestVerification.missing,0);assert.equal(value.manifestVerification.unexpected,0);assert.equal(value.manifestVerification.duplicates,0);assert.equal(value.manifestVerification.exactValues,true);assert.equal(value.manifestVerification.fingerprints,true);assert.equal(value.manifestVerification.status,true);});
test("P6-B-R1 preserva auditoria e dados operacionais",()=>{if(!existsSync(resultPath))return;const value=JSON.parse(readFileSync(resultPath,"utf8"));assert.equal(value.auditSemantics.creationExpected,0);assert.equal(value.auditSemantics.creationActual,0);assert.equal(value.databaseAfter.audit,value.databaseBefore.audit);assert.equal(value.databaseAfter.products,value.databaseBefore.products);assert.equal(value.databaseAfter.variants,value.databaseBefore.variants);assert.equal(value.databaseAfter.prices,value.databaseBefore.prices);assert.equal(value.databaseAfter.inventory,value.databaseBefore.inventory);assert.equal(value.databaseAfter.profiles,value.databaseBefore.profiles);assert.equal(value.databaseAfter.approvals,value.databaseBefore.approvals);assert.equal(value.databaseAfter.publications,value.databaseBefore.publications);});
test("P6-B-R1 prova idempotencia e zero IA",()=>{if(!existsSync(resultPath))return;const value=JSON.parse(readFileSync(resultPath,"utf8"));assert.deepEqual(value.idempotencyRecheck,{alreadyExistsExact:2322,wouldInsert:0,conflicting:0});assert.equal(value.openAiCalls,0);assert.equal(value.aiCostUsd,"0");assert.equal(value.pimAiEnabledFinal,false);assert.equal(value.stagingAuditWrites,0);assert.equal(value.production,"NO");assert.equal(value.woocommerce,"unchanged");assert.equal(value.olist,"unchanged");assert.equal(value.media,"unchanged");});
