import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import test from "node:test";
const read=path=>readFileSync(new URL(`../${path}`,import.meta.url),"utf8");

test("P6-D cria armazenamento normalizado, RLS e identidade idempotente",()=>{const migration=read("supabase/migrations/20260901233000_pim_conflicts.sql");assert.match(migration,/create table public\.pim_conflicts/);assert.match(migration,/enable row level security/);assert.match(migration,/pim_conflicts_logical_identity_unique/);assert.match(migration,/source_fingerprint/);assert.match(migration,/evidence_fingerprint/);assert.doesNotMatch(migration,/create policy/i);});
test("P6-D persiste somente classificações ainda bloqueantes",()=>{const migration=read("supabase/migrations/20260901233000_pim_conflicts.sql"),script=read("scripts/database/pim-ai-p6d-conflict-persistence.mjs");assert.match(migration,/true_source_contradiction/);assert.match(migration,/unresolved_ambiguity/);for(const resolved of ["LEGITIMATE_MULTI_VALUE","SEMANTIC_ROLE_SEPARATION","COMPOUND_MEASURE","EXTRACTION_FALSE_POSITIVE","NORMALIZATION_FALSE_POSITIVE"])assert.match(script,new RegExp(resolved));});
test("P6-D usa fingerprint, transação e escrita idempotente sem auditoria inventada",()=>{const script=read("scripts/database/pim-ai-p6d-conflict-persistence.mjs");assert.match(script,/sourceFingerprint/);assert.match(script,/FRESH_EXACT/);assert.match(script,/sql\.begin/);assert.match(script,/on conflict/);assert.doesNotMatch(script,/insert into pim_audit_log/i);assert.match(script,/PIM_AI_ENABLED="false"/);});
test("P6-D painel consulta conflitos PIM e exibe evidência",()=>{const repository=read("lib/pim/repository.ts"),page=read("app/admin/products/[id]/page.tsx");assert.match(repository,/from pim_conflicts/);assert.doesNotMatch(repository,/external_mappings em where em\.internal_id=p\.id and em\.status='conflict'/);assert.match(page,/product\.conflicts/);assert.match(page,/Ver evidências das fontes/);});
