import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {auditCompactEvidenceBindings} from "../lib/pim/evidence-catalog.ts";
import {normalizeMeasurement} from "../lib/pim/normalization.ts";

const output=(attribute,value,ref="e1")=>({suggestedName:"Teste",shortDescription:"Teste",longDescription:"Teste",bulletPoints:["Teste"],application:"Teste",attributes:[{attribute,value,evidenceRefs:[ref]}],seo:{title:"Teste",metaDescription:"Teste",searchTerms:["teste"]},uncertainties:[]}),catalog=(attribute,value,productReference="p1")=>{const entry={id:"e1",attribute,value,sourceType:"SOURCE_TITLE",sourceReference:"title"},normalizedValue=normalizeMeasurement(value);return{entries:[entry],productReference,byId:new Map([["e1",{entry,evidence:{sourceType:"SOURCE_TITLE",sourceReference:"title",rawValue:value,normalizedValue,confidence:1,extractionMethod:"test"},allowedAttributes:[attribute],normalizedValue,unit:null,compound:/ x /.test(value)}]])};};
test("representações canônicas de polegada com ponto final são equivalentes",()=>{assert.equal(normalizeMeasurement("3/8 pol."),'3/8"');assert.equal(normalizeMeasurement("3/8 pol"),'3/8"');assert.equal(normalizeMeasurement('3/8"'),'3/8"');assert.deepEqual(auditCompactEvidenceBindings(output("thread","3/8 pol."),catalog("thread",'3/8"'),{expectedProductReference:"p1"}),[]);});
test("match exato, unidade suportada, composto e restauração canônica passam",()=>{assert.deepEqual(auditCompactEvidenceBindings(output("voltage","240V"),catalog("voltage","240V")),[]);assert.deepEqual(auditCompactEvidenceBindings(output("diameter","13 mm"),catalog("diameter","13mm")),[]);assert.deepEqual(auditCompactEvidenceBindings(output("bitola",'25mm x 3/4"'),catalog("bitola",'25mm x 3/4"')),[]);assert.deepEqual(auditCompactEvidenceBindings(output("thread","3/8 pol"),catalog("thread",'3/8"')),[]);});
test("range, claim técnico, atributo, produto, unidade e expansão sem suporte bloqueiam",()=>{assert.ok(auditCompactEvidenceBindings(output("voltage","100-240V"),catalog("voltage","240V")).length);assert.ok(auditCompactEvidenceBindings(output("voltage","220V"),catalog("voltage","240V")).length);assert.ok(auditCompactEvidenceBindings(output("line","LYS"),catalog("bitola","220 x 28mm")).length);assert.equal(auditCompactEvidenceBindings(output("thread",'3/8"'),catalog("thread",'3/8"',"p2"),{expectedProductReference:"p1"})[0].code,"CROSS_PRODUCT_FOREIGN_REF");assert.ok(auditCompactEvidenceBindings(output("diameter","13mm"),catalog("diameter","13")).length);assert.ok(auditCompactEvidenceBindings(output("thread",'3/8" - 1/2"'),catalog("thread",'3/8"')).length);});
test("relatório preserva histórico e mantém readiness 50 sem executar",async()=>{const report=JSON.parse(await readFile("supabase/.temp/pim-ai/p5b-r1-p9-analysis/analysis-report.json","utf8"));assert.equal(report.historicalArtifactsPreserved,true);assert.equal(report.revalidated.length,10);assert.ok(report.revalidated.every(item=>item.evidenceValidation==="PASS"));assert.equal(report.eligibleHistorical,9);assert.equal(report.quarantinedHistorical,1);assert.equal(report.scaleReadiness50,"PASS");assert.equal(report.openAiCalls,0);assert.equal(report.stagingWrites,0);});
