import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync,existsSync} from "node:fs";

const manifest=JSON.parse(readFileSync("supabase/.temp/pim-ai/p4b-r4/preflight-manifest.json","utf8"));
test("R4 manifest preserva contrato compacto e zero rede OpenAI",()=>{assert.equal(manifest.phase,"P.4-B-R4-PREFLIGHT");assert.deepEqual(manifest.contract,{...manifest.contract,model:"gpt-5.4-mini",promptVersion:"pim-enrichment-v4",schemaVersion:"pim-structured-output-v3",outputPolicyVersion:"pim-output-policy-v2",maxOutputTokens:1200,targetOutputTokens:750});assert.equal(manifest.realRequestAttempts,0);assert.equal(manifest.realAiCalls,0);assert.equal(manifest.realAiCostUsdMicros,"0");assert.equal(manifest.dryRequestsBuilt,2);});
test("D e E estao atuais, seguros e dentro do budget realista",()=>{assert.equal(manifest.products.length,2);for(const product of manifest.products){assert.equal(product.sourceStale,false);assert.equal(product.safeContextDiff,"NO_CHANGE");assert.equal(product.materialContextChange,false);assert.equal(product.unexpectedContextChange,false);assert.equal(product.dlp,"PASS");assert.equal(product.promptInjection,"PASS");assert.deepEqual(product.forbiddenFields,[]);assert.equal(product.evidenceCatalogStable,true);assert.equal(product.requestBuilt,true);assert.equal(product.requestSent,false);assert.ok(product.estimatedRealisticOutputTokens<=800);assert.ok(product.marginTo1200>0);assert.equal(product.r3R4FingerprintDifferent,true);assert.equal(product.pilotEligible,true);}});
test("ownership e enforcement permanecem hard gates",()=>{assert.equal(manifest.ownershipTest,"PASS");assert.equal(manifest.invalidRefBlock,"PASS");assert.equal(manifest.foreignRefBlock,"PASS");assert.equal(manifest.unsupportedValueBlock,"PASS");assert.equal(manifest.conflictEnforcement,"PASS");assert.ok(manifest.historicalRegressions.every(item=>item.pass&&item.blockingConflicts.length===0&&item.unsupportedFacts.length===0));});
test("markers R4 respeitam o lifecycle e o staging preflight foi somente leitura",()=>{const dPath="supabase/.temp/pim-ai/p4b-r4/p4b-r4-d.json";const ePath="supabase/.temp/pim-ai/p4b-r4/p4b-r4-e.json";const markersExist=existsSync(dPath)||existsSync(ePath);if(markersExist){assert.equal(existsSync(dPath),true);assert.equal(existsSync(ePath),true);const d=JSON.parse(readFileSync(dPath,"utf8"));const e=JSON.parse(readFileSync(ePath,"utf8"));assert.equal(d.state,"COMPLETED");assert.equal(e.state,"COMPLETED");assert.equal(d.test,"P4B-R4-D");assert.equal(e.test,"P4B-R4-E");}else{assert.equal(existsSync(dPath),false);assert.equal(existsSync(ePath),false);}assert.equal(manifest.stagingReads,2);assert.equal(manifest.stagingWrites,0);assert.ok(BigInt(manifest.recommendedHardBudgetUsdMicros)<=20000n);});
test("resultado real R4 preserva budgets e zero mutacao quando presente",()=>{const resultPath="supabase/.temp/pim-ai/p4b-r4/p4b-r4-results.json";if(!existsSync(resultPath))return;const {summary}=JSON.parse(readFileSync(resultPath,"utf8"));assert.equal(summary.attempts,2);assert.equal(summary.responses,2);assert.equal(summary.retries,0);assert.ok(BigInt(summary.spentUsdMicros)<=BigInt(summary.hardBudgetUsdMicros));assert.equal(summary.remoteMutations,0);assert.equal(summary.stagingWrites,0);assert.equal(summary.pimAiEnabledFinal,false);});
