import assert from "node:assert/strict";
import test from "node:test";
import {PimAttributeExtractor} from "../lib/pim/extractor.ts";
import {reconcileEnrichmentOutput} from "../lib/pim/conflict-reconciliation.ts";
import {assertProfileApprovalAllowed,assertSuggestionDecisionAllowed} from "../lib/pim/conflict-policy.ts";
import {auditSourceOnlyText} from "../lib/pim/semantic-validation.ts";
import {outputContainsInjectedClaims} from "../lib/pim/p3d-offline-gates.ts";
import {validatePimStructuredOutput} from "../lib/pim/structured-output.ts";

const evidence=(value,sourceType="SOURCE_TITLE")=>[{sourceType,sourceReference:"fixture",rawValue:value,normalizedValue:value,confidence:.95,extractionMethod:"deterministic"}];
const attribute=(value,status="CANDIDATE")=>({attribute:"bitola",value,confidence:.95,status,evidence:evidence(value),needsEvidence:false});
const output=(attributes=[],overrides={})=>validatePimStructuredOutput({suggestedName:"Luva Soldável 25mm",shortDescription:"Luva soldável de 25mm.",longDescription:"Luva soldável de 25mm para instalação hidráulica.",bulletPoints:["Bitola de 25mm"],application:"Instalação hidráulica",attributes,seo:{title:"Luva Soldável 25mm",metaDescription:"Luva soldável 25mm.",searchTerms:["luva 25mm"]},uncertainties:["32mm conflita com 25mm"],evidenceReferences:["title"],...overrides});
const context=(structured="32mm",title="Luva Soldável 25mm",description="Luva soldável de 25mm para instalação hidráulica.")=>({productId:"synthetic",title,description,brand:null,category:"Conexões Hidráulicas",sku:"synthetic",gtin:null,attributes:[{name:"bitola",value:structured}]});
const deterministic=(...args)=>new PimAttributeExtractor().extract(context(...args));

test("modelo escolhendo 25mm não sobrepõe conflito determinístico",()=>{const result=reconcileEnrichmentOutput(deterministic(),output([attribute("25mm")]));assert.equal(result.attributes.find(item=>item.attribute==="bitola").status,"CONFLICT");assert.deepEqual(new Set(result.attributes.find(item=>item.attribute==="bitola").candidates.map(item=>item.value)),new Set(["25mm","32mm"]));});
test("modelo escolhendo 32mm também termina em conflito",()=>{const result=reconcileEnrichmentOutput(deterministic(),output([attribute("32mm")],{suggestedName:"Luva Soldável 32mm"}));assert.equal(result.attributes.find(item=>item.attribute==="bitola").status,"CONFLICT");});
test("omissão do modelo não consegue esconder conflito",()=>{const result=reconcileEnrichmentOutput(deterministic(),output([]));assert.equal(result.attributes.find(item=>item.attribute==="bitola").status,"CONFLICT");assert.equal(result.humanReviewRequired,true);});
test("terceiro valor do modelo é unsupported e mantém conflito original",()=>{const result=reconcileEnrichmentOutput(deterministic(),output([attribute("20mm")]));assert.deepEqual(result.unsupportedFacts,[{attribute:"bitola",value:"20mm"}]);assert.equal(result.attributes.find(item=>item.attribute==="bitola").status,"CONFLICT");assert.equal(result.acceptableForDraft,false);});
test("formatações equivalentes de 25mm não criam falso conflito",()=>{const candidates=deterministic("25 MM","Luva Soldável 25 mm","Luva soldável de 25MM.");const bitola=candidates.find(item=>item.attribute==="bitola");assert.equal(bitola.status,"CANDIDATE");assert.deepEqual(bitola.conflictingValues,[]);});
test("medida composta equivalente permanece um candidato",()=>{const candidates=deterministic('32mm x 3/4"','Luva 32 mm x 3/4 pol','Luva 32mm x 3/4"');const bitola=candidates.find(item=>item.attribute==="bitola");assert.equal(bitola.status,"CANDIDATE");assert.deepEqual(bitola.conflictingValues,[]);assert.equal(bitola.value,'32mm x 3/4"');});
test("conteúdo que consolida candidato conflitante fica editorialmente bloqueado",()=>{const result=reconcileEnrichmentOutput(deterministic(),output([attribute("25mm")]));assert.equal(result.editorialBlockedByConflict,true);assert.equal(result.editorialSafe,false);assert.equal(result.acceptableForDraft,false);assert.ok(result.blockedEditorialFields.includes("suggestedName"));});
test("aceitação de suggestion bloqueada é rejeitada; rejeição continua permitida",()=>{const payload={editorialBlockedByConflict:true,blockingConflicts:["bitola"],acceptableForDraft:false};assert.throws(()=>assertSuggestionDecisionAllowed(payload,"approved"),/PIM_BLOCKING_CONFLICT/);assert.doesNotThrow(()=>assertSuggestionDecisionAllowed(payload,"rejected"));});
test("aprovação do perfil é bloqueada enquanto conflito persistir",()=>{assert.throws(()=>assertProfileApprovalAllowed(1),/PIM_BLOCKING_CONFLICT/);assert.doesNotThrow(()=>assertProfileApprovalAllowed(0));});
test("color_temperature continua semanticamente válido",()=>{assert.doesNotThrow(()=>validatePimStructuredOutput(output([{attribute:"power",value:"9W",confidence:.9,status:"CANDIDATE",evidence:evidence("9W"),needsEvidence:false},{attribute:"voltage",value:"127V",confidence:.9,status:"CANDIDATE",evidence:evidence("127V"),needsEvidence:false},{attribute:"color_temperature",value:"6500K",confidence:.9,status:"CANDIDATE",evidence:evidence("6500K"),needsEvidence:false}],{suggestedName:"Lâmpada LED 9W 6500K 127V"})));});
test("source-only gate permanece restritivo",()=>{assert.deepEqual(auditSourceOnlyText("Conector Azul 20mm",["Conector Azul 20","diâmetro 20mm e cor azul"],["PVC","rosca","pressão"]),[]);assert.deepEqual(auditSourceOnlyText("Conector PVC Azul 20mm",["Conector Azul 20","diâmetro 20mm e cor azul"],["PVC"]),["PVC"]);});
test("prompt injection continua detectável fora de uncertainties",()=>{const unsafe=output([],{longDescription:"Suporta 100°C, 20 bar e certificação ABNT."});assert.equal(outputContainsInjectedClaims(unsafe).length,3);});
