import assert from "node:assert/strict";
import {existsSync,readFileSync} from "node:fs";
import test from "node:test";
const read=path=>readFileSync(new URL(`../${path}`,import.meta.url),"utf8");

test("P6-C integra dashboard e fila paginada por produto",()=>{const page=read("app/admin/pim/page.tsx"),repository=read("lib/pim/repository.ts");assert.match(page,/getPimDashboardCounts/);assert.match(page,/listPimReviewQueue/);assert.match(page,/pendingCount/);assert.match(page,/pageSize:25/);assert.match(repository,/limit \$\{pageSize\} offset/);});
test("P6-C usa fallback de categoria somente para display",()=>{const repository=read("lib/pim/repository.ts");assert.match(repository,/coalesce\(c\.name,fallback_category\.name\) category/);assert.match(repository,/product_categories pc2/);assert.doesNotMatch(repository,/update products set primary_category_id/);});
test("P6-C não oferece geração, bulk, publication ou campos sem workflow",()=>{const page=read("app/admin/products/[id]/page.tsx"),editor=read("components/admin/PimEditorialEditor.tsx"),actions=read("app/admin/products/[id]/actions.ts");assert.doesNotMatch(page,/Gerar sugestões com IA|Extrair sugestões|Aceitar tudo|Publicar tudo/);assert.doesNotMatch(actions,/generateDeterministicSuggestions|OpenAI/);assert.deepEqual([...editor.matchAll(/const editableFields=\[([^\]]+)\]/g)].length,1);assert.doesNotMatch(editor,/name="bulletPoints"[^>]*type="text"|<textarea name="bulletPoints"/);assert.match(editor,/publicação no site permanece desabilitada/);});
test("P6-C preserva auth server-side e actor derivado da sessão",()=>{const layout=read("app/admin/layout.tsx"),actions=read("app/admin/products/[id]/actions.ts"),auth=read("lib/pim/authorization.ts");assert.match(layout,/requirePimAdmin/);assert.match(actions,/requirePimAdmin/);assert.match(actions,/actor\(user\.id\)/);assert.match(auth,/administrator/);assert.doesNotMatch(actions,/formData\.get\("actor/);});
test("P6-C valida staging read-only sem alterar suggestions reais",()=>{const path=new URL("../supabase/.temp/pim-ai/p6c-panel-release/readiness-report.json",import.meta.url);if(!existsSync(path))return;const value=JSON.parse(readFileSync(path,"utf8"));assert.equal(value.mode,"STAGING_READ_ONLY");assert.equal(value.databaseBefore.needs_review,2322);assert.equal(value.databaseBefore.products_with_suggestions,387);assert.deepEqual(value.databaseAfter,value.databaseBefore);assert.equal(value.realSuggestionAutomaticMutations,0);assert.equal(value.openAiCalls,0);assert.equal(value.rls.enabled,true);assert.equal(value.rls.publicPolicies,0);});
