import test from "node:test";
import assert from "node:assert/strict";
import {zodTextFormat} from "openai/helpers/zod";
import {PIM_OUTPUT_LIMITS,PIM_OUTPUT_POLICY_VERSION,PIM_SCHEMA_VERSION,PIM_TARGET_OUTPUT_TOKENS} from "../lib/pim/ai-output-policy.ts";
import {PIM_PROMPT_VERSION} from "../lib/pim/enrichment-types.ts";
import {pimCompactStructuredOutputSchema,validatePimCompactStructuredOutput} from "../lib/pim/compact-structured-output.ts";
import {buildPimEvidenceCatalog,resolveCompactEvidence} from "../lib/pim/evidence-catalog.ts";
import {createPimAiRequestFingerprint} from "../lib/pim/pilot-preparation.ts";

const evidence=(sourceReference,value,sourceType="SOURCE_ATTRIBUTE")=>({sourceType,sourceReference,rawValue:value,normalizedValue:value,confidence:.97,extractionMethod:"structured_source"});
const candidate=(attribute,value,items=[evidence(`attribute:${attribute}`,value)])=>({attribute,value,rawValue:value,unit:null,confidence:.97,confidenceBand:"HIGH",status:"CANDIDATE",evidence:items,conflictingValues:[]});
const output=(attributes=[])=>({suggestedName:"Produto tecnico compacto",shortDescription:"Descricao curta factual.",longDescription:"Descricao objetiva sem repetir todos os atributos nem a fonte original.",bulletPoints:["Beneficio factual novo","Caracteristica evidenciada","Aplicacao objetiva"],application:"Uso conforme a fonte do produto.",attributes,seo:{title:"Produto tecnico compacto",metaDescription:"Produto tecnico com descricao factual e objetiva.",searchTerms:["produto tecnico","marca"]},uncertainties:[]});

test("contrato v4/v3/v2 e schema estrito sao versionados",()=>{assert.equal(PIM_PROMPT_VERSION,"pim-enrichment-v4");assert.equal(PIM_SCHEMA_VERSION,"pim-structured-output-v3");assert.equal(PIM_OUTPUT_POLICY_VERSION,"pim-output-policy-v2");assert.equal(PIM_TARGET_OUTPUT_TOKENS,750);const format=zodTextFormat(pimCompactStructuredOutputSchema,"pim_enrichment_v4");assert.equal(format.strict,true);assert.equal(format.schema.additionalProperties,false);assert.ok(JSON.stringify(format).includes('"maxItems"'));});
test("catalogo de evidence e estavel e normaliza duplicatas",()=>{const candidates=[candidate("color","branco",[evidence("title","branco","SOURCE_TITLE"),evidence("title","branco","SOURCE_TITLE")]),candidate("brand","Marca")];const first=buildPimEvidenceCatalog(candidates),second=buildPimEvidenceCatalog([...candidates].reverse());assert.deepEqual(first.entries,second.entries);assert.equal(first.entries.length,2);});
test("adapter resolve refs e calcula status/confidence no backend",()=>{const catalog=buildPimEvidenceCatalog([candidate("color","branco")]),ref=catalog.entries[0].id,compact=validatePimCompactStructuredOutput(output([{attribute:"color",value:"Branco",evidenceRefs:[ref,ref]}])),resolved=resolveCompactEvidence(compact,catalog);assert.equal(resolved.attributes[0].status,"CANDIDATE");assert.equal(resolved.attributes[0].confidence,.97);assert.equal(resolved.attributes[0].evidence.length,1);});
test("refs invalidas, estrangeiras e semanticamente divergentes sao bloqueadas",()=>{const catalog=buildPimEvidenceCatalog([candidate("color","branco"),candidate("brand","Marca")]),color=catalog.entries.find(item=>item.attribute==="color").id,brand=catalog.entries.find(item=>item.attribute==="brand").id;assert.throws(()=>resolveCompactEvidence(output([{attribute:"color",value:"branco",evidenceRefs:["e99"]}]),catalog),/INVALID_EVIDENCE_REF/);assert.throws(()=>resolveCompactEvidence(output([{attribute:"color",value:"branco",evidenceRefs:[brand]}]),catalog),/FOREIGN_EVIDENCE_REF/);assert.throws(()=>resolveCompactEvidence(output([{attribute:"color",value:"preto",evidenceRefs:[color]}]),catalog),/SEMANTIC_EVIDENCE_MISMATCH/);});
test("bounds compactos e integridade semantica",()=>{assert.equal(PIM_OUTPUT_LIMITS.attributeCount,10);assert.equal(PIM_OUTPUT_LIMITS.evidencePerAttribute,2);assert.throws(()=>validatePimCompactStructuredOutput(output([{attribute:"voltage",value:"10mm",evidenceRefs:["e1"]}])));assert.doesNotThrow(()=>validatePimCompactStructuredOutput(output([{attribute:"bitola",value:'25mm x 3/4"',evidenceRefs:["e1"]},{attribute:"current",value:"25A",evidenceRefs:["e2"]},{attribute:"voltage",value:"600V",evidenceRefs:["e3"]},{attribute:"diameter",value:"10mm",evidenceRefs:["e4"]}])));});
test("fingerprint R4 difere de R3",()=>{const common={safeContextFingerprint:"safe",model:"gpt-5.4-mini"},r3=createPimAiRequestFingerprint({...common,promptVersion:"pim-enrichment-v3",schemaVersion:"pim-structured-output-v2",outputPolicyVersion:"pim-output-policy-v1"}),r4=createPimAiRequestFingerprint({...common,promptVersion:PIM_PROMPT_VERSION,schemaVersion:PIM_SCHEMA_VERSION,outputPolicyVersion:PIM_OUTPUT_POLICY_VERSION});assert.notEqual(r3,r4);assert.equal(r4,createPimAiRequestFingerprint({...common,promptVersion:PIM_PROMPT_VERSION,schemaVersion:PIM_SCHEMA_VERSION,outputPolicyVersion:PIM_OUTPUT_POLICY_VERSION}));});
test("golden compact dataset cobre oito perfis",()=>{const fixtures=["simple","compound hydraulic","electrical","rich D-like","incomplete E-like","conflict","missing data","prompt injection"];for(const [index,name] of fixtures.entries()){const value=output(index===1?[{attribute:"bitola",value:'25mm x 3/4"',evidenceRefs:["e1"]}]:[]);assert.doesNotThrow(()=>validatePimCompactStructuredOutput(value),name);}assert.equal(fixtures.length,8);});
