import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";

const base="supabase/.temp/pim-ai/p5b-r1",load=name=>readFile(`${base}/${name}`,"utf8").then(JSON.parse);
test("P5-B-R1 consumiu exatamente sete one-shots dentro do budget",async()=>{const result=await load("recovery-results.json");assert.equal(result.summary.attempts,7);assert.equal(result.summary.responses,7);assert.equal(result.summary.openAiCalls,7);assert.equal(result.summary.retries,0);assert.ok(BigInt(result.summary.spentUsdMicros)<=50000n);assert.equal(result.summary.hardBudgetUsdMicros,"50000");assert.equal(result.summary.batchStop,null);});
test("P5-B-R1 preservou banco e não persistiu outputs",async()=>{const result=await load("recovery-results.json");assert.deepEqual(result.summary.before,result.summary.after);assert.equal(result.summary.remoteMutations,0);assert.equal(result.summary.stagingWrites,0);assert.equal(result.summary.persistenceWrites,0);assert.equal(result.summary.pimAiEnabledFinal,false);});
test("P5-B-R1 aprovou seis produtos e quarentenou expansão local de P9",async()=>{const result=await load("recovery-results.json");assert.deepEqual(result.results.map(item=>item.index),[4,5,6,7,8,10]);assert.ok(result.results.every(item=>item.classification==="PASS"&&item.eligibleForFutureSuggestion===true&&item.persistencePerformed===false));assert.equal(result.quarantine.length,1);assert.equal(result.quarantine[0].index,9);assert.equal(result.quarantine[0].classification,"LOCAL_VALIDATION_FAILURE");assert.match(result.quarantine[0].reason,/UNSUPPORTED_VALUE_EXPANSION/);});
test("P5-B-R1 markers são completos e separados do namespace histórico",async()=>{const batch=await load("recovery-batch-marker.json");assert.equal(batch.state,"COMPLETED");for(const index of [4,5,6,7,8,9,10]){const marker=await load(`recovery-product-${String(index).padStart(2,"0")}.json`);assert.equal(marker.state,"COMPLETED");assert.equal(marker.responses,1);}assert.equal(batch.attempts,7);assert.equal(batch.retries,0);});
