import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";

const base="supabase/.temp/pim-ai/p5c-r1",load=name=>readFile(`${base}/${name}`,"utf8").then(JSON.parse);
test("P5-C-R1 respeitou resume, one-shots e budget",async()=>{const result=await load("resume-results.json");assert.equal(result.phase,"P.5-C-R1-REAL-AI");assert.equal(result.summary.authorizedProducts.length,44);assert.equal(result.summary.authorizedProducts[0],7);assert.equal(result.summary.attempts,33);assert.equal(result.summary.responses,33);assert.equal(result.summary.retries,0);assert.ok(BigInt(result.summary.spentUsdMicros)<=350000n);assert.equal(result.summary.hardBudgetUsdMicros,"350000");});
test("P5-C-R1 interrompeu na segunda foreign evidence estrutural",async()=>{const result=await load("resume-results.json");assert.equal(result.summary.batchStop,"SYSTEMIC_PATTERN:FOREIGN_EVIDENCE_REF:2_PRODUCTS");assert.equal(result.results.filter(item=>item.classification==="PASS").length,26);assert.equal(result.results.filter(item=>item.classification==="QUALITY_REVIEW_FAILURE").length,5);assert.equal(result.quarantine.length,7);assert.equal(result.quarantine.filter(item=>typeof item.reason==="string"&&item.reason.includes("SAME_PRODUCT_SEMANTICALLY_FOREIGN_REF")).length,2);});
test("P5-C-R1 preservou staging e manteve IA desligada",async()=>{const result=await load("resume-results.json");assert.deepEqual(result.summary.before,result.summary.after);assert.equal(result.summary.remoteMutations,0);assert.equal(result.summary.stagingWrites,0);assert.equal(result.summary.persistenceWrites,0);assert.equal(result.summary.pimAiEnabledFinal,false);});
test("P5-C-R1 possui 33 markers completos e nao repetiu os seis historicos",async()=>{const batch=await load("resume-batch-marker.json");assert.equal(batch.state,"COMPLETED");for(let index=7;index<=39;index+=1){const marker=await load(`resume-product-${String(index).padStart(2,"0")}.json`);assert.equal(marker.state,"COMPLETED");assert.equal(marker.responses,1);}assert.equal(batch.attempts,33);assert.equal(batch.retries,0);});
