import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import test from "node:test";
import {PimAttributeExtractor} from "../lib/pim/extractor.ts";
import {extractMeasurements,normalizeMeasurement} from "../lib/pim/normalization.ts";
import {createPimSourceFingerprint} from "../lib/pim/fingerprint.ts";
import {validatePimStructuredOutput} from "../lib/pim/structured-output.ts";
import {MockPimEnrichmentProvider} from "../lib/pim/enrichment-provider.ts";

const fixtures=JSON.parse(await readFile(new URL("./fixtures/pim-enrichment-golden.json",import.meta.url),"utf8"));
const context=(fixture)=>({productId:"00000000-0000-4000-8000-000000000001",title:fixture.title,description:fixture.description,brand:fixture.brand,category:fixture.category,sku:`TEST-${fixture.id}`,gtin:null,attributes:[]});

test("golden dataset determinístico preserva fatos presentes",()=>{const extractor=new PimAttributeExtractor();for(const fixture of fixtures){const result=extractor.extract(context(fixture));for(const [attribute,expected] of Object.entries(fixture.expected)){const found=result.find(item=>item.attribute===attribute);assert.ok(found,`${fixture.id}:${attribute}`);if(expected==="CONFLICT")assert.equal(found.status,"CONFLICT");else assert.equal(found.value,expected,`${fixture.id}:${attribute}`);}}});
test("medidas compostas permanecem valores canônicos únicos",()=>{for(const value of ['25mm x 1/2"','16mm x 1/2"','32mm x 3/4"','20mm x 1/2"','32 x 25mm'])assert.deepEqual(extractMeasurements(value).map(x=>x.normalized),[value]);});
test("normalização cobre unidades sem inferir número isolado",()=>{for(const [raw,expected] of [["25 MM","25mm"],["25 mm","25mm"],["3/4 pol",'3/4"'],["220 V","220V"],["20 A","20A"],["500 W","500W"]])assert.equal(normalizeMeasurement(raw),expected);assert.deepEqual(extractMeasurements("modelo 20"),[]);});
test("conflito 220V versus 127V não escolhe vencedor",()=>{const [voltage]=new PimAttributeExtractor().extract(context(fixtures.find(x=>x.id==="conflict"))).filter(x=>x.attribute==="voltage");assert.equal(voltage.status,"CONFLICT");assert.deepEqual(new Set(voltage.conflictingValues),new Set(["220V","127V"]));});
test("prompt injection permanece somente dado",()=>{const result=new PimAttributeExtractor().extract(context(fixtures.at(-1)));assert.equal(result.length,0);});
test("output estruturado rejeita JSON arbitrário e fatos sem evidence",()=>{assert.throws(()=>validatePimStructuredOutput({approve:true}));assert.throws(()=>validatePimStructuredOutput({suggestedName:null,shortDescription:null,longDescription:null,bulletPoints:[],application:null,attributes:[{attribute:"voltage",value:"220V",confidence:.9,status:"CANDIDATE",evidence:[]}],seo:{title:null,metaDescription:null,searchTerms:[]},uncertainties:[],evidenceReferences:[]}));});
test("output estruturado válido preserva incerteza",()=>{const value=validatePimStructuredOutput({suggestedName:null,shortDescription:null,longDescription:null,bulletPoints:[],application:null,attributes:[],seo:{title:null,metaDescription:null,searchTerms:[]},uncertainties:["marca ausente"],evidenceReferences:[]});assert.deepEqual(value.uncertainties,["marca ausente"]);});
test("source fingerprint é determinístico e muda com a origem",()=>{const first=context(fixtures[0]);assert.equal(createPimSourceFingerprint(first),createPimSourceFingerprint({...first}));assert.notEqual(createPimSourceFingerprint(first),createPimSourceFingerprint({...first,title:`${first.title} novo`}));assert.match(createPimSourceFingerprint(first),/^[a-f0-9]{64}$/);});
test("mock provider não realiza chamada externa",async()=>{const provider=new MockPimEnrichmentProvider([{fieldName:"commercialName",suggestedValue:"Nome",confidence:.8,evidence:"title"}]);assert.equal(provider.providerId,"mock");assert.equal((await provider.enrichProduct({})).suggestions[0].suggestedValue,"Nome");});
test("migration P.3 não toca domínios operacionais nem cria policy pública",async()=>{const migration=await readFile(new URL("../supabase/migrations/20260828220000_pim_ai_enrichment_foundation.sql",import.meta.url),"utf8");assert.doesNotMatch(migration,/update\s+(products|product_variants|prices|inventory_levels|external_mappings)/i);assert.doesNotMatch(migration,/create\s+policy/i);});
test("admin exige autorização e IA real permanece desabilitada",async()=>{const [actions,panel,provider]=await Promise.all([readFile(new URL("../app/admin/products/[id]/actions.ts",import.meta.url),"utf8"),readFile(new URL("../components/admin/PimEnrichmentPanel.tsx",import.meta.url),"utf8"),readFile(new URL("../lib/pim/enrichment-provider.ts",import.meta.url),"utf8")]);assert.match(actions,/requirePimAdmin/);assert.match(panel,/disabled/);assert.doesNotMatch(provider,/fetch\(|OpenAI|axios/);});
