import type { CatalogProduct } from "./domain.ts";

export type CatalogProductRow=Record<string,unknown>;
const asDate=(value:unknown)=>value instanceof Date?value.toISOString():typeof value==="string"?new Date(value).toISOString():null;
const asArray=<T>(value:unknown):T[]=>Array.isArray(value)?value as T[]:[];
const asBigInt=(value:unknown)=>BigInt(String(value??0));

export function mapPostgresProductRow(row:CatalogProductRow):CatalogProduct {
  const taxonomy=(item:Record<string,unknown>)=>({externalId:Number(item.externalId),name:String(item.name),slug:String(item.slug),description:String(item.description??""),parentExternalId:item.parentExternalId==null?null:Number(item.parentExternalId),image:item.imageUrl?{url:String(item.imageUrl),alt:String(item.imageAlt??"")}:null,productCount:item.productCount==null?undefined:Number(item.productCount)});
  const categories=asArray<Record<string,unknown>>(row.categories).map(taxonomy);
  const images=asArray<Record<string,unknown>>(row.images).map((item)=>({externalId:item.externalId===null?null:Number(item.externalId),url:String(item.url),alt:String(item.alt??""),title:item.title===null?null:String(item.title),role:String(item.role),position:Number(item.position)}));
  const attributes=asArray<Record<string,unknown>>(row.attributes).map((item)=>({code:String(item.code),name:String(item.name),value:String(item.value)}));
  const brandRow=row.brand&&typeof row.brand==="object"?row.brand as Record<string,unknown>:null,quantity=asBigInt(row.quantityAvailable),status=String(row.wooStockStatus)==="onbackorder"?"on-backorder" as const:String(row.wooStockStatus)==="instock"||row.wooStockStatus==null&&quantity>BigInt(0)?"in-stock" as const:"out-of-stock" as const;
  const inventory={quantityAvailable:quantity,status,manageStock:Boolean(row.manageStock),purchasable:Boolean(row.purchasable),allowsBackorder:Boolean(row.allowsBackorder),available:Boolean(row.purchasable)&&(status!=="out-of-stock"||Boolean(row.allowsBackorder))};
  const price={currency:String(row.currency),regularMinor:asBigInt(row.regularMinor),saleMinor:row.saleMinor===null?null:asBigInt(row.saleMinor),saleValidFrom:asDate(row.saleValidFrom),saleValidTo:asDate(row.saleValidTo)};
  const variants=asArray<Record<string,unknown>>(row.variants).map((item)=>({externalId:item.externalId==null?null:Number(item.externalId),internalId:item.internalId==null?null:String(item.internalId),sku:String(item.sku),gtin:item.gtin==null?null:String(item.gtin),status:String(item.status),price:{currency:String(item.currency),regularMinor:asBigInt(item.regularMinor),saleMinor:item.saleMinor==null?null:asBigInt(item.saleMinor),saleValidFrom:asDate(item.saleValidFrom),saleValidTo:asDate(item.saleValidTo)},inventory:{...inventory,quantityAvailable:asBigInt(item.quantityAvailable)},attributes:asArray<Record<string,unknown>>(item.attributes).map((term)=>({code:String(term.code),name:String(term.name),value:String(term.value)})),isDefault:String(item.sku)===String(row.sku)}));
  return{source:"postgres",externalId:Number(row.externalId),internalId:String(row.internalId),slug:String(row.slug),name:String(row.name),sku:String(row.sku),gtin:row.gtin===null?null:String(row.gtin),status:String(row.status),type:String(row.type??"simple"),shortDescription:String(row.shortDescription??""),description:String(row.description??""),publishedAt:asDate(row.publishedAt),price,inventory,brand:brandRow?taxonomy(brandRow):null,categories,images,attributes,variants,defaultVariantSku:String(row.sku),tags:asArray<Record<string,unknown>>(row.tags).map(taxonomy),visibility:String(row.visibility??"visible"),featured:Boolean(row.featured),popularity:asBigInt(row.popularity),averageRating:Number(row.averageRating??0),reviewCount:Number(row.reviewCount??0),freeShipping:Boolean(row.freeShipping)};
}
