"use client";
import Image from "next/image";
import Link from "next/link";
import { Heart, ShoppingCart, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { useFavorites } from "@/hooks/useFavorites";
import { getProductHref } from "@/lib/routing/storefrontUrls";

interface FavoriteProduct { id:number; slug:string; name:string; image?:{src:string;alt:string}; price:number; regularPrice?:number; currencyCode:string; brand?:string; available:boolean; }
const money=(value:number,currency:string)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency}).format(value);
export function FavoritesPageClient(){
  const {favorites,removeFavorite,isReady}=useFavorites(); const [products,setProducts]=useState<FavoriteProduct[]>([]); const [loading,setLoading]=useState(true); const [failed,setFailed]=useState(false);
  useEffect(()=>{if(!isReady)return;const controller=new AbortController();void Promise.resolve().then(async()=>{if(!favorites.length){setProducts([]);setLoading(false);return;}setLoading(true);setFailed(false);const r=await fetch(`/api/catalog/favorites?ids=${favorites.join(",")}`,{signal:controller.signal});if(!r.ok)throw new Error();const body=await r.json() as {products:FavoriteProduct[]};setProducts(body.products);}).catch((e:unknown)=>{if(!(e instanceof DOMException&&e.name==="AbortError"))setFailed(true);}).finally(()=>setLoading(false));return()=>controller.abort();},[favorites,isReady]);
  if(!isReady||loading)return <p role="status" className="py-16 text-center text-muted">Carregando seus favoritos…</p>;
  if(failed)return <p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-6 text-center text-red-800">Não foi possível carregar seus produtos favoritos agora.</p>;
  if(!favorites.length)return <div className="py-14 text-center"><Heart className="mx-auto h-12 w-12 text-secondary" aria-hidden="true"/><p className="mt-5 text-lg font-semibold text-foreground">Você ainda não possui produtos favoritos.</p><p className="mt-2 text-muted">Adicione produtos clicando no coração.</p><Link href="/" className="mt-7 inline-flex rounded-xl bg-secondary px-5 py-3 font-semibold text-white hover:bg-secondary-hover focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary">Continuar comprando</Link></div>;
  return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{products.map((product)=>{const href=getProductHref(product.slug);return <article key={product.id} className="flex flex-col rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><Link href={href} className="relative block aspect-square overflow-hidden rounded-xl bg-white">{product.image?<Image src={product.image.src} alt={product.image.alt||product.name} fill sizes="(min-width:1024px) 30vw, 50vw" className="object-contain p-4"/>:null}</Link><p className="mt-3 text-xs font-medium uppercase tracking-wide text-muted">{product.brand||"Persi Materiais"}</p><Link href={href} className="mt-1 font-semibold text-foreground hover:text-secondary">{product.name}</Link><p className="mt-3 text-lg font-bold text-emerald-700">{money(product.price,product.currencyCode)} <span className="text-xs">no Pix</span></p><p className={`mt-1 text-sm font-medium ${product.available?"text-emerald-700":"text-muted"}`}>{product.available?"Disponível":"Indisponível"}</p><div className="mt-auto grid grid-cols-2 gap-2 pt-5"><Link href={href} className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-3 py-2.5 text-sm font-semibold text-white hover:bg-primary-hover"><ShoppingCart size={17}/> {product.available?"Comprar":"Ver produto"}</Link><button type="button" onClick={()=>void removeFavorite(product.id)} className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-300 px-3 py-2.5 text-sm font-semibold text-foreground hover:border-red-300 hover:text-red-700" aria-label={`Remover ${product.name} dos favoritos`}><Trash2 size={17}/>Remover</button></div><Link href={href} className="mt-3 text-center text-sm font-semibold text-primary underline-offset-4 hover:underline">Ver Produto</Link></article>;})}</div>;
}
