import type { CatalogProduct, CatalogVariant } from "@/lib/catalog/domain";
import type { Product } from "@/types/product";

const toMinor=(value:number|undefined,minorUnit:number)=>value===undefined?null:BigInt(Math.round(value*10**minorUnit));

export function mapWooProductToCatalog(product:Product):CatalogProduct {
  const minorUnit=product.currencyMinorUnit,regular=toMinor(product.regularPrice??product.price,minorUnit)??BigInt(0),sale=toMinor(product.salePrice,minorUnit);
  const price={currency:product.currencyCode,regularMinor:regular,saleMinor:sale,saleValidFrom:null,saleValidTo:null},quantity=BigInt(product.stockQuantity??0),inventory={quantityAvailable:quantity,status:product.stockStatus==="onbackorder"?"on-backorder" as const:product.available?"in-stock" as const:"out-of-stock" as const,manageStock:product.stockQuantity!==undefined,purchasable:product.isPurchasable??product.available,allowsBackorder:product.variations.some((item)=>item.backordersAllowed===true),available:product.available};
  const attributes=product.attributes.flatMap((attribute)=>attribute.options.map((option)=>({code:attribute.taxonomy??attribute.name,name:attribute.name,value:option.label}))),variants:CatalogVariant[]=product.variations.map((item)=>({externalId:item.id,internalId:null,sku:item.sku??"",gtin:null,status:item.inStock?"active":"draft",price:{currency:product.currencyCode,regularMinor:toMinor(item.regularPrice??item.price,minorUnit)??BigInt(0),saleMinor:toMinor(item.salePrice,minorUnit),saleValidFrom:null,saleValidTo:null},inventory:{...inventory,quantityAvailable:BigInt(item.stockQuantity??0),purchasable:item.purchasable,allowsBackorder:item.backordersAllowed??false,available:item.inStock&&item.purchasable},attributes:item.attributes.map((a)=>({code:a.name,name:a.name,value:a.value})),isDefault:false}));
  return{source:"woocommerce",externalId:product.id,internalId:null,slug:product.slug,name:product.name,sku:product.sku,gtin:product.ean??null,status:"active",type:product.type??"simple",shortDescription:product.shortDescription,description:product.description,publishedAt:product.dateCreated??null,price,inventory,brand:product.brands[0]?{externalId:product.brands[0].id,name:product.brands[0].name,slug:product.brands[0].slug}:null,categories:product.categories.map((item)=>({externalId:item.id,name:item.name,slug:item.slug,description:item.description,parentExternalId:item.parent,image:item.image?{url:item.image.src,alt:item.image.alt}:null,productCount:item.count})),images:product.images.map((item,index)=>({externalId:item.id??null,url:item.src,alt:item.alt,title:item.name??null,role:index===0?"primary":"gallery",position:index})),attributes,variants,defaultVariantSku:product.sku,tags:[],visibility:"visible",featured:product.featured,popularity:BigInt(product.totalSales??0),averageRating:product.averageRating,reviewCount:product.reviewCount,freeShipping:product.freeShipping??false};
}
