<?php defined( 'ABSPATH' ) || exit;
$status_labels = array( 'ATTRIBUTE_ALREADY_SYNCED' => 'Já preenchido', 'ATTRIBUTE_CANDIDATE' => 'Novo valor encontrado', 'ATTRIBUTE_CONFLICT' => 'Conflito', 'ATTRIBUTE_MAPPING_REQUIRED' => 'Definir atributo de destino', 'ATTRIBUTE_REVIEW_REQUIRED' => 'Revisão necessária', 'ATTRIBUTE_NO_VALUE' => 'Sem valor', 'ATTRIBUTE_UNSUPPORTED_CONTEXT' => 'Contexto não suportado', 'ATTRIBUTE_SKIPPED' => 'Ignorado' );
$concept_labels = array( 'cor' => 'Cor', 'corrente_nominal' => 'Corrente nominal', 'potencia' => 'Potência', 'tensao' => 'Tensão', 'bitola' => 'Bitola', 'secao_nominal' => 'Seção nominal', 'numero_polos' => 'Número de polos', 'comprimento' => 'Comprimento', 'diametro' => 'Diâmetro', 'rosca' => 'Rosca', 'medida_nao_classificada' => 'Medida não classificada' );
$family_labels = array( 'electrical_breaker' => 'Disjuntores elétricos', 'electrical_wire_cable' => 'Fios e cabos elétricos', 'electrical_switchgear' => 'Dispositivos elétricos', 'hydraulic_pipe' => 'Tubos hidráulicos', 'hydraulic_fitting' => 'Conexões hidráulicas', 'pump' => 'Bombas', 'shower' => 'Chuveiros', 'tool' => 'Ferramentas', 'generic' => 'Genérica' );
$source_labels = array( 'WOO_EXISTING' => 'Atributo existente no WooCommerce', 'OLIST_STRUCTURED' => 'Campo estruturado do Olist', 'MANUAL_MAPPING' => 'Mapeamento manual', 'TITLE_PATTERN' => 'Padrão encontrado no título', 'DESCRIPTION_LABEL_VALUE' => 'Campo identificado na descrição' );
$confidence_labels = array( 'EXACT_STRUCTURED' => 'Exata / estruturada', 'HIGH_CONTEXTUAL' => 'Alta pelo contexto', 'MEDIUM_CONTEXTUAL' => 'Média pelo contexto', 'REVIEW_REQUIRED' => 'Requer revisão' );
$status_labels = array_merge( $status_labels, array( 'ATTRIBUTE_TERM_MATCHED' => 'Já existe no WooCommerce', 'ATTRIBUTE_TERM_MAPPING_REQUIRED' => 'Termo ou taxonomia requer mapeamento', 'ATTRIBUTE_UNIT_AMBIGUOUS' => 'Unidade ambígua', 'ATTRIBUTE_CONCEPT_AMBIGUOUS' => 'Conceito ambíguo', 'ATTRIBUTE_SOURCE_CONFLICT' => 'Conflito entre fontes', 'ATTRIBUTE_UNSUPPORTED_UNIT' => 'Unidade não suportada', 'ATTRIBUTE_DESTINATION_MISSING' => 'Taxonomia de destino ainda não criada' ) );
$concept_labels = array_merge( $concept_labels, array( 'secao_condutor' => 'Seção do condutor', 'potencia_aparente' => 'Potência aparente', 'fase' => 'Fase', 'espessura' => 'Espessura', 'largura_fita' => 'Largura da fita', 'dn_composto' => 'DN composto', 'medida_composta' => 'Medida composta' ) );
$source_labels['REJECTED_DISCOVERY'] = 'Descoberta rejeitada para bitola pelo contexto';
$confidence_labels = array_merge( $confidence_labels, array( 'HIGH_CONTEXT' => 'Alta pelo contexto', 'MEDIUM_CONTEXT' => 'Média pelo contexto', 'LOW_CONTEXT' => 'Baixa pelo contexto' ) );
$filter_label = static function ( string $key, string $value ) use ( $status_labels, $concept_labels, $source_labels, $confidence_labels, $family_labels ): string { $sets = array( 'status' => $status_labels, 'attribute_key' => $concept_labels, 'source' => $source_labels, 'confidence' => $confidence_labels, 'family' => $family_labels ); return $sets[ $key ][ $value ] ?? $value; };
?>
<div class="wrap">
	<h1>Atributos Persi</h1><div class="notice notice-info inline"><p><strong>Somente diagnóstico:</strong> nenhum atributo, taxonomia ou termo é criado ou alterado nesta versão.</p></div>
	<?php if ( $mapping_notice ) : ?><div class="notice notice-info inline"><p><?php echo esc_html( $mapping_notice ); ?></p></div><?php endif; ?>
	<h2>Atributos globais existentes no WooCommerce</h2>
	<table class="widefat striped"><thead><tr><th>Nome</th><th>Taxonomia</th><th>Termos</th><th>Produtos usando</th><th>Possível conceito</th></tr></thead><tbody><?php foreach ( $attributes as $attribute ) : ?><tr><td><?php echo esc_html( $attribute['name'] ); ?></td><td><code><?php echo esc_html( $attribute['taxonomy'] ); ?></code></td><td><?php echo esc_html( (string) $attribute['terms'] ); ?></td><td><?php echo esc_html( (string) $attribute['products'] ); ?></td><td><?php echo esc_html( $concept_labels[ $attribute['canonical'] ] ?? 'Revisão necessária' ); ?><?php if ( $attribute['duplicate'] ) : ?> <strong>— possível sobreposição</strong><?php endif; ?></td></tr><?php endforeach; ?><?php if ( ! $attributes ) : ?><tr><td colspan="5">Nenhum atributo global encontrado.</td></tr><?php endif; ?></tbody></table>

	<h2>Matriz de mapeamento</h2><p>Relaciona um campo de origem a uma taxonomia que já existe. A opção de escrita automática permanece desativada e não funcional.</p>
	<div class="notice notice-info inline"><p><strong>Mapeamentos automáticos pelo conceito + unidade:</strong><br><?php foreach ( $automatic_mappings as $automatic ) : ?><?php echo esc_html( 'medida_composta' === $automatic['concept'] ? 'Medida composta' : 'Bitola em ' . $automatic['unit'] ); ?> → <code><?php echo esc_html( $automatic['taxonomy'] ); ?></code> — <?php echo esc_html( $automatic['configured'] ? 'Configurado' : 'Taxonomia ainda não criada' ); ?><br><?php endforeach; ?>A matriz manual permanece disponível para exceções e campos específicos.</p></div>
	<form method="post"><?php wp_nonce_field( 'persi_attribute_mapping' ); ?><input type="hidden" name="persi_mapping" value="1"><table class="form-table"><tbody>
		<tr><th><label for="origin_key">Campo/alias de origem</label></th><td><input id="origin_key" name="origin_key" required maxlength="191"></td></tr>
		<tr><th><label for="family">Família opcional</label></th><td><select id="family" name="family"><option value="">Todas as famílias</option><?php foreach ( $family_labels as $key => $label ) : ?><option value="<?php echo esc_attr( $key ); ?>"><?php echo esc_html( $label ); ?></option><?php endforeach; ?></select></td></tr>
		<tr><th><label for="category_id">ID da categoria</label></th><td><input id="category_id" name="category_id" type="number" min="0" value="0"><p class="description">0 = todas as categorias.</p></td></tr>
		<tr><th><label for="attribute_key">Conceito canônico</label></th><td><select id="attribute_key" name="attribute_key" required><option value="">Selecione</option><?php foreach ( $concept_labels as $key => $label ) : if ( 'medida_nao_classificada' === $key ) { continue; } ?><option value="<?php echo esc_attr( $key ); ?>"><?php echo esc_html( $label ); ?></option><?php endforeach; ?></select></td></tr>
		<tr><th><label for="woo_taxonomy">Atributo destino</label></th><td><select id="woo_taxonomy" name="woo_taxonomy" required><option value="">Selecione</option><?php foreach ( $attributes as $attribute ) : ?><option value="<?php echo esc_attr( $attribute['taxonomy'] ); ?>"><?php echo esc_html( $attribute['name'] . ' — ' . $attribute['taxonomy'] ); ?></option><?php endforeach; ?></select></td></tr>
		<tr><th><label for="normalizer">Normalizador</label></th><td><select id="normalizer" name="normalizer"><option value="">Automático pelo conceito</option><option value="ampere">Ampere</option><option value="volt">Volt</option><option value="watt">Watt</option><option value="millimeter">Milímetro</option></select></td></tr>
	</tbody></table><?php submit_button( 'Salvar mapeamento para próximos diagnósticos' ); ?></form>
	<table class="widefat striped"><thead><tr><th>Origem</th><th>Família</th><th>Categoria</th><th>Conceito</th><th>Destino</th><th>Escrita automática</th></tr></thead><tbody><?php foreach ( $mappings as $mapping ) : ?><tr><td><?php echo esc_html( $mapping->origin_key ); ?></td><td><?php echo esc_html( $family_labels[ $mapping->family ?? '' ] ?? 'Todas' ); ?></td><td><?php echo esc_html( $mapping->category_id ? (string) $mapping->category_id : 'Todas' ); ?></td><td><?php echo esc_html( $concept_labels[ $mapping->attribute_key ] ?? $mapping->attribute_key ); ?></td><td><code><?php echo esc_html( $mapping->woo_taxonomy ); ?></code></td><td>DESATIVADA</td></tr><?php endforeach; ?><?php if ( ! $mappings ) : ?><tr><td colspan="6">Nenhum mapeamento manual aprovado.</td></tr><?php endif; ?></tbody></table>

	<h2>Diagnóstico de atributos <?php echo $run_id ? '#'.esc_html( (string) $run_id ) : ''; ?></h2>
	<?php if ( $summary ) : ?><p><strong>Produtos analisados:</strong> <?php echo esc_html( (string) $summary['products'] ); ?></p><div class="persi-attribute-summary"><?php foreach ( $summary['statuses'] as $item ) : ?><span><strong><?php echo esc_html( $status_labels[ $item->status ] ?? $item->status ); ?>:</strong> <?php echo esc_html( (string) $item->total ); ?></span><?php endforeach; ?></div>
	<h3>Candidatos por conceito</h3><div class="persi-attribute-summary"><?php foreach ( $summary['concepts'] as $item ) : ?><span><?php echo esc_html( $concept_labels[ $item->attribute_key ] ?? $item->attribute_key ); ?>: <?php echo esc_html( (string) $item->total ); ?></span><?php endforeach; ?></div>
	<h3>Ocorrências por regra</h3><div class="persi-attribute-summary"><?php foreach ( $summary['rules'] as $item ) : ?><span><?php echo esc_html( ( $source_labels[ $item->source ] ?? $item->source ) . ' / ' . ( $item->rule_id ?: 'sem regra' ) ); ?>: <?php echo esc_html( (string) $item->total ); ?></span><?php endforeach; ?></div><?php endif; ?>

	<form method="get" class="persi-attribute-filters"><input type="hidden" name="page" value="persi-catalog-attributes"><input type="hidden" name="run_id" value="<?php echo esc_attr( (string) $run_id ); ?>"><?php foreach ( array( 'status' => 'Situação', 'attribute_key' => 'Conceito', 'source' => 'Origem', 'confidence' => 'Confiança', 'family' => 'Família' ) as $key => $label ) : ?><label><?php echo esc_html( $label ); ?><select name="<?php echo esc_attr( $key ); ?>"><option value="">Todos</option><?php foreach ( $filter_values[ $key ] ?? array() as $value ) : ?><option value="<?php echo esc_attr( $value ); ?>" <?php selected( $filters[ $key ], $value ); ?>><?php echo esc_html( $filter_label( $key, $value ) ); ?></option><?php endforeach; ?></select></label><?php endforeach; ?><label><input type="checkbox" name="show_synced" value="1" <?php checked( isset( $_GET['show_synced'] ) ); ?>> Mostrar já preenchidos</label><label><input type="checkbox" name="show_rejected" value="1" <?php checked( isset( $_GET['show_rejected'] ) ); ?>> Mostrar candidatos rejeitados</label><?php submit_button( 'Filtrar', 'secondary', '', false ); ?></form>

	<table class="widefat striped"><thead><tr><th>Produto / SKU</th><th>Categoria / família</th><th>Conceito</th><th>Original → normalizado / unidade</th><th>Origem / confiança</th><th>Destino / termo Woo</th><th>Situação</th><th>Detalhes</th></tr></thead><tbody><?php foreach ( $candidates as $candidate ) : ?><tr><td><?php echo esc_html( $candidate->product_name ?: '#'.$candidate->product_id ); ?><br><code><?php echo esc_html( $candidate->sku ?: 'sem SKU' ); ?></code></td><td><?php echo esc_html( $candidate->category_path ?: 'Sem categoria' ); ?><br><small><?php echo esc_html( $family_labels[ $candidate->family ] ?? $candidate->family ); ?></small></td><td><?php echo esc_html( $concept_labels[ $candidate->attribute_key ] ?? $candidate->attribute_key ); ?></td><td><?php echo esc_html( $candidate->raw_value ); ?> → <strong><?php echo esc_html( $candidate->normalized_value ); ?></strong><br><small>Unidade: <?php echo esc_html( $candidate->unit ?: '—' ); ?></small></td><td><?php echo esc_html( $source_labels[ $candidate->source ] ?? $candidate->source ); ?><br><small><?php echo esc_html( $confidence_labels[ $candidate->confidence ] ?? $candidate->confidence ); ?></small></td><td><code><?php echo esc_html( $candidate->woo_taxonomy ?: 'Não mapeado' ); ?></code><br><small><?php echo esc_html( $candidate->existing_term ?: 'Termo não encontrado' ); ?></small></td><td><?php echo esc_html( $status_labels[ $candidate->status ] ?? $candidate->status ); ?><br><small><code><?php echo esc_html( $candidate->status ); ?></code></small></td><td><details><summary>Ver evidência</summary><p><strong>Fonte/campo:</strong> <?php echo esc_html( $candidate->source . ' / ' . ( $candidate->source_field ?: '—' ) ); ?><br><strong>Trecho:</strong> <?php echo esc_html( $candidate->evidence ?: '—' ); ?><br><strong>Match:</strong> <?php echo esc_html( $candidate->raw_value ); ?><br><strong>Normalização:</strong> <?php echo esc_html( $candidate->normalized_value ); ?><br><strong>Regra:</strong> <code><?php echo esc_html( $candidate->rule_id ?: '—' ); ?></code><br><strong>Versão:</strong> <?php echo esc_html( $candidate->ruleset_version ?: '—' ); ?></p></details></td></tr><?php endforeach; ?><?php if ( ! $candidates ) : ?><tr><td colspan="8">Nenhum candidato corresponde aos filtros. Execute uma Simulação com o módulo Atributos.</td></tr><?php endif; ?></tbody></table>
</div>
