export const PIM_SCHEMA_VERSION="pim-structured-output-v3";
export const PIM_OUTPUT_POLICY_VERSION="pim-output-policy-v2";
export const PIM_TARGET_OUTPUT_TOKENS=750;
export const PIM_OUTPUT_LIMITS={displayName:120,shortDescription:220,shortDescriptionTarget:180,longDescription:700,longDescriptionTargetMin:300,longDescriptionTargetMax:600,bulletCount:5,bulletLength:120,application:240,applicationTarget:180,attributeCount:10,attributeValue:180,evidencePerAttribute:2,evidenceReferences:12,evidenceReferenceLength:12,seoTitle:70,metaDescription:160,searchTerms:8,searchTermLength:40,uncertainties:3,uncertaintyLength:140} as const;

type ProviderResponseLike={id?:unknown;status?:unknown;incomplete_details?:unknown;output_text?:unknown;output?:unknown;error?:unknown;usage?:{input_tokens?:unknown;input_tokens_details?:{cached_tokens?:unknown};output_tokens?:unknown;total_tokens?:unknown}};
const safeText=(value:unknown)=>typeof value==="string"?value:null;
const safeNumber=(value:unknown)=>typeof value==="number"&&Number.isFinite(value)?value:null;
function outputItems(value:unknown){if(!Array.isArray(value))return[];return value.map(item=>{if(!item||typeof item!=="object")return{type:null,status:null,content:[]};const record=item as Record<string,unknown>,content=Array.isArray(record.content)?record.content.map(part=>part&&typeof part==="object"?{type:safeText((part as Record<string,unknown>).type),status:safeText((part as Record<string,unknown>).status),refusal:safeText((part as Record<string,unknown>).refusal)}:{type:null,status:null,refusal:null}):[];return{id:safeText(record.id),type:safeText(record.type),status:safeText(record.status),role:safeText(record.role),content};});}
export function diagnoseOpenAiStructuredResponse(response:ProviderResponseLike,parsedOutput:unknown,maxOutputTokens:number){
 const responseStatus=safeText(response.status),incompleteDetails=response.incomplete_details&&typeof response.incomplete_details==="object"?response.incomplete_details:null,incompleteReason=incompleteDetails&&"reason" in incompleteDetails?safeText((incompleteDetails as Record<string,unknown>).reason):null,outputTokens=safeNumber(response.usage?.output_tokens),providerParsedOutputAvailable=parsedOutput!==null&&parsedOutput!==undefined,items=outputItems(response.output),refusal=items.some(item=>item.content.some(part=>Boolean(part.refusal))),providerIncomplete=responseStatus==="incomplete"||Boolean(incompleteReason),outputLimitReached=incompleteReason==="max_output_tokens"||(outputTokens!==null&&outputTokens>=maxOutputTokens),classification=providerParsedOutputAvailable?"PARSED_OUTPUT_AVAILABLE":refusal?"OUTPUT_PARSED_NULL_REFUSAL":providerIncomplete?"OUTPUT_PARSED_NULL_INCOMPLETE_RESPONSE":outputLimitReached?"OUTPUT_PARSED_NULL_WITH_OUTPUT_LIMIT":response.error?"OUTPUT_PARSED_NULL_PROVIDER_ERROR":"OUTPUT_PARSED_NULL_UNKNOWN";
 return{classification,responseId:safeText(response.id),responseStatus,incompleteDetails,incompleteReason,providerResponseComplete:responseStatus==="completed"?true:providerIncomplete?false:null,providerParsedOutputAvailable,outputLimitReached:outputLimitReached?true:outputTokens===null?null:false,usage:{inputTokens:safeNumber(response.usage?.input_tokens),cachedInputTokens:safeNumber(response.usage?.input_tokens_details?.cached_tokens),outputTokens,totalTokens:safeNumber(response.usage?.total_tokens)},rawOutputText:safeText(response.output_text),outputItems:items,refusal,providerError:response.error&&typeof response.error==="object"?{code:safeText((response.error as Record<string,unknown>).code),type:safeText((response.error as Record<string,unknown>).type)}:null,localZodExecuted:false,localZodResult:"NOT_EXECUTED" as const};
}
