import {z} from "zod";
import {PIM_OUTPUT_LIMITS,PIM_SCHEMA_VERSION} from "./ai-output-policy.ts";
import {PIM_ATTRIBUTE_CODES} from "./enrichment-types.ts";
import {auditSemanticUnit} from "./semantic-validation.ts";

const compactAttribute=z.object({attribute:z.enum(PIM_ATTRIBUTE_CODES),value:z.string().trim().min(1).max(PIM_OUTPUT_LIMITS.attributeValue),evidenceRefs:z.array(z.string().regex(/^e[1-9]\d*$/).max(PIM_OUTPUT_LIMITS.evidenceReferenceLength)).min(1).max(PIM_OUTPUT_LIMITS.evidencePerAttribute)}).strict().superRefine((value,context)=>{const mismatch=auditSemanticUnit(value.attribute,value.value);if(mismatch)context.addIssue({code:"custom",message:`${mismatch.code}:${mismatch.attribute}:${mismatch.unit}`,path:["value"]});});
export const pimCompactStructuredOutputSchema=z.object({suggestedName:z.string().trim().min(1).max(PIM_OUTPUT_LIMITS.displayName).nullable(),shortDescription:z.string().trim().max(PIM_OUTPUT_LIMITS.shortDescription).nullable(),longDescription:z.string().trim().max(PIM_OUTPUT_LIMITS.longDescription).nullable(),bulletPoints:z.array(z.string().trim().min(1).max(PIM_OUTPUT_LIMITS.bulletLength)).max(PIM_OUTPUT_LIMITS.bulletCount),application:z.string().trim().max(PIM_OUTPUT_LIMITS.application).nullable(),attributes:z.array(compactAttribute).max(PIM_OUTPUT_LIMITS.attributeCount),seo:z.object({title:z.string().trim().max(PIM_OUTPUT_LIMITS.seoTitle).nullable(),metaDescription:z.string().trim().max(PIM_OUTPUT_LIMITS.metaDescription).nullable(),searchTerms:z.array(z.string().trim().min(1).max(PIM_OUTPUT_LIMITS.searchTermLength)).max(PIM_OUTPUT_LIMITS.searchTerms)}).strict(),uncertainties:z.array(z.string().trim().min(1).max(PIM_OUTPUT_LIMITS.uncertaintyLength)).max(PIM_OUTPUT_LIMITS.uncertainties)}).strict().superRefine((value,context)=>{const refs=value.attributes.flatMap(item=>item.evidenceRefs);if(new Set(refs).size>PIM_OUTPUT_LIMITS.evidenceReferences)context.addIssue({code:"custom",message:"MAX_TOTAL_EVIDENCE_REFS",path:["attributes"]});});
export {PIM_SCHEMA_VERSION};
export type PimCompactStructuredOutput=z.infer<typeof pimCompactStructuredOutputSchema>;
export function validatePimCompactStructuredOutput(value:unknown){return pimCompactStructuredOutputSchema.parse(value);}
