import type {PimAttributeCandidate,PimAttributeCode,PimEvidence} from "./enrichment-types.ts";
import type {PimCompactStructuredOutput} from "./compact-structured-output.ts";
import type {PimStructuredOutput} from "./structured-output.ts";
import {detectUnit,normalizeMeasurement} from "./normalization.ts";

export type PimEvidenceCatalogEntry={id:string;attribute:PimAttributeCode;value:string;sourceType:PimEvidence["sourceType"];sourceReference:string};
export type PimEvidenceDescriptor={entry:PimEvidenceCatalogEntry;evidence:PimEvidence;allowedAttributes:readonly PimAttributeCode[];normalizedValue:string;unit:string|null;compound:boolean;sourceStatus:PimAttributeCandidate["status"]};
export type PimEvidenceCatalog={entries:PimEvidenceCatalogEntry[];byId:Map<string,PimEvidenceDescriptor>;productReference:string|null};
export type EvidenceBindingFailure={code:"INVALID_EVIDENCE_REF"|"CROSS_PRODUCT_FOREIGN_REF"|"SAME_PRODUCT_SEMANTICALLY_FOREIGN_REF"|"UNSUPPORTED_EVIDENCE_VALUE"|"UNSUPPORTED_VALUE_EXPANSION";ref:string;attribute:PimAttributeCode;modelValue:string;evidenceAttribute?:PimAttributeCode;evidenceValue?:string};
export type EvidenceReboundAudit={attribute:PimAttributeCode;modelValue:string;rejectedRefs:string[];boundRef:string;decision:"MODEL_EVIDENCE_REF_REJECTED_DETERMINISTIC_EVIDENCE_REBOUND"};
export type EvidenceValueRelation="EXACT_MATCH"|"CANONICAL_EQUIVALENCE"|"MISSING_UNIT_RESTORABLE"|"COMPOUND_REPRESENTATION"|"EXPANSION"|"NARROWING"|"UNSUPPORTED_VALUE";

export function buildPimEvidenceCatalog(candidates:ReadonlyArray<PimAttributeCandidate>,options:{productReference?:string}={}):PimEvidenceCatalog{
 const records=candidates.flatMap(candidate=>candidate.evidence.map(evidence=>({attribute:candidate.attribute,evidence,status:candidate.status}))).sort((a,b)=>`${a.attribute}|${a.evidence.sourceType}|${a.evidence.sourceReference}|${a.evidence.normalizedValue}`.localeCompare(`${b.attribute}|${b.evidence.sourceType}|${b.evidence.sourceReference}|${b.evidence.normalizedValue}`)),byKey=new Map<string,typeof records[number]>();
 for(const record of records){const key=`${record.attribute}|${record.evidence.sourceType}|${record.evidence.sourceReference}|${normalizeMeasurement(record.evidence.normalizedValue||record.evidence.rawValue).toLocaleLowerCase("pt-BR")}`;if(!byKey.has(key))byKey.set(key,record);}
 const byId=new Map<string,PimEvidenceDescriptor>(),entries=[...byKey.values()].map((record,index)=>{const normalizedValue=normalizeMeasurement(record.evidence.normalizedValue||record.evidence.rawValue),entry={id:`e${index+1}`,attribute:record.attribute,value:normalizedValue,sourceType:record.evidence.sourceType,sourceReference:record.evidence.sourceReference};byId.set(entry.id,{entry,evidence:record.evidence,allowedAttributes:[record.attribute],normalizedValue,unit:detectUnit(normalizedValue),compound:/\s[xX]\s/.test(normalizedValue),sourceStatus:record.status});return entry;});return{entries,byId,productReference:options.productReference??null};
}

const folded=(value:string)=>normalizeMeasurement(value).toLocaleLowerCase("pt-BR");
const atomic=(value:string)=>{const match=folded(value).match(/^(\d+(?:[.,]\d+)?)\s*(mm|cm|ml|kg|kw|cv|hp|v|a|w|k|l|m|g|")?$/);return match?{magnitude:match[1].replace(",","."),unit:match[2]??null}:null;};
export function classifyEvidenceValue(modelValue:string,evidenceValue:string):EvidenceValueRelation{if(modelValue.trim()===evidenceValue.trim())return"EXACT_MATCH";const model=folded(modelValue),evidence=folded(evidenceValue);if(model===evidence)return/[xX]/.test(model)?"COMPOUND_REPRESENTATION":"CANONICAL_EQUIVALENCE";const m=atomic(model),e=atomic(evidence);if(m&&e&&m.magnitude===e.magnitude&&!m.unit&&e.unit)return"MISSING_UNIT_RESTORABLE";if((model.includes(evidence)&&model!==evidence)||/[–—-]/.test(model)&&model.split(/[–—-]/).some(part=>part.trim()===evidence))return"EXPANSION";if(evidence.includes(model)&&model!==evidence)return"NARROWING";return"UNSUPPORTED_VALUE";}

export function auditCompactEvidenceBindings(output:PimCompactStructuredOutput,catalog:PimEvidenceCatalog,options:{expectedProductReference?:string}={}):EvidenceBindingFailure[]{const failures:EvidenceBindingFailure[]=[];for(const item of output.attributes)for(const ref of [...new Set(item.evidenceRefs)]){const match=catalog.byId.get(ref),base={ref,attribute:item.attribute,modelValue:item.value};if(!match){failures.push({code:"INVALID_EVIDENCE_REF",...base});continue;}if(options.expectedProductReference&&catalog.productReference&&options.expectedProductReference!==catalog.productReference){failures.push({code:"CROSS_PRODUCT_FOREIGN_REF",...base,evidenceAttribute:match.entry.attribute,evidenceValue:match.entry.value});continue;}if(!match.allowedAttributes.includes(item.attribute)){failures.push({code:"SAME_PRODUCT_SEMANTICALLY_FOREIGN_REF",...base,evidenceAttribute:match.entry.attribute,evidenceValue:match.entry.value});continue;}if(match.sourceStatus==="CONFLICT"){failures.push({code:"UNSUPPORTED_EVIDENCE_VALUE",...base,evidenceAttribute:match.entry.attribute,evidenceValue:match.entry.value});continue;}const relation=classifyEvidenceValue(item.value,match.normalizedValue);if(!["EXACT_MATCH","CANONICAL_EQUIVALENCE","COMPOUND_REPRESENTATION","MISSING_UNIT_RESTORABLE"].includes(relation))failures.push({code:relation==="EXPANSION"?"UNSUPPORTED_VALUE_EXPANSION":"UNSUPPORTED_EVIDENCE_VALUE",...base,evidenceAttribute:match.entry.attribute,evidenceValue:match.entry.value});}return failures;}

export function rebindCompactEvidence(output:PimCompactStructuredOutput,catalog:PimEvidenceCatalog){const audits:EvidenceReboundAudit[]=[],attributes=output.attributes.map(item=>{const failures=auditCompactEvidenceBindings({...output,attributes:[item]},catalog);if(!failures.length||failures.some(failure=>failure.code!=="SAME_PRODUCT_SEMANTICALLY_FOREIGN_REF"))return item;const compatible=[...catalog.byId.values()].filter(descriptor=>descriptor.sourceStatus!=="CONFLICT"&&descriptor.allowedAttributes.includes(item.attribute)&&["EXACT_MATCH","CANONICAL_EQUIVALENCE","COMPOUND_REPRESENTATION","MISSING_UNIT_RESTORABLE"].includes(classifyEvidenceValue(item.value,descriptor.normalizedValue)));if(compatible.length!==1)return item;const boundRef=compatible[0].entry.id;audits.push({attribute:item.attribute,modelValue:item.value,rejectedRefs:[...item.evidenceRefs],boundRef,decision:"MODEL_EVIDENCE_REF_REJECTED_DETERMINISTIC_EVIDENCE_REBOUND"});return{...item,evidenceRefs:[boundRef]};});return{output:{...output,attributes},audits};}

export function resolveCompactEvidence(output:PimCompactStructuredOutput,catalog:PimEvidenceCatalog,options:{expectedProductReference?:string}={}):PimStructuredOutput{const effective=rebindCompactEvidence(output,catalog).output,failures=auditCompactEvidenceBindings(effective,catalog,options);if(failures.length){const failure=failures[0],legacyCode=failure.code==="SAME_PRODUCT_SEMANTICALLY_FOREIGN_REF"?"FOREIGN_EVIDENCE_REF":failure.code==="UNSUPPORTED_EVIDENCE_VALUE"||failure.code==="UNSUPPORTED_VALUE_EXPANSION"?"SEMANTIC_EVIDENCE_MISMATCH":failure.code;throw new Error(`${legacyCode}:${failure.code}:${failure.ref}`);}const attributes=effective.attributes.map(item=>{const refs=[...new Set(item.evidenceRefs)],descriptors=refs.map(ref=>catalog.byId.get(ref)).filter((value):value is PimEvidenceDescriptor=>Boolean(value)),resolved=descriptors.map(item=>item.evidence),confidence=Math.min(...resolved.map(item=>item.confidence)),restorable=descriptors.filter(descriptor=>classifyEvidenceValue(item.value,descriptor.entry.value)==="MISSING_UNIT_RESTORABLE");if(restorable.length&&new Set(descriptors.map(descriptor=>folded(descriptor.entry.value))).size!==1)throw new Error(`SEMANTIC_EVIDENCE_MISMATCH:AMBIGUOUS_UNIT_RESTORATION:${refs[0]}`);const value=restorable.length?restorable[0].entry.value:item.value;return{attribute:item.attribute,value,confidence,status:"CANDIDATE" as const,evidence:resolved,needsEvidence:false};});return{suggestedName:effective.suggestedName,shortDescription:effective.shortDescription,longDescription:effective.longDescription,bulletPoints:effective.bulletPoints,application:effective.application,attributes,seo:effective.seo,uncertainties:effective.uncertainties,evidenceReferences:[...new Set(effective.attributes.flatMap(item=>item.evidenceRefs))]};}
