import type {PimAttributeCandidate,PimAttributeCode,PimEvidence} from "./enrichment-types.ts";
import type {PimCompactStructuredOutput} from "./compact-structured-output.ts";
import type {PimStructuredOutput} from "./structured-output.ts";
import {detectUnit,normalizeMeasurement} from "./normalization.ts";

export type PimEvidenceCatalogEntry={id:string;attribute:PimAttributeCode;value:string;sourceType:PimEvidence["sourceType"];sourceReference:string};
export type PimEvidenceDescriptor={entry:PimEvidenceCatalogEntry;evidence:PimEvidence;allowedAttributes:readonly PimAttributeCode[];normalizedValue:string;unit:string|null;compound:boolean};
export type PimEvidenceCatalog={entries:PimEvidenceCatalogEntry[];byId:Map<string,PimEvidenceDescriptor>;productReference:string|null};
export type EvidenceBindingFailure={code:"INVALID_EVIDENCE_REF"|"CROSS_PRODUCT_FOREIGN_REF"|"SAME_PRODUCT_SEMANTICALLY_FOREIGN_REF"|"UNSUPPORTED_EVIDENCE_VALUE"|"UNSUPPORTED_VALUE_EXPANSION";ref:string;attribute:PimAttributeCode;modelValue:string;evidenceAttribute?:PimAttributeCode;evidenceValue?:string};

export function buildPimEvidenceCatalog(candidates:ReadonlyArray<PimAttributeCandidate>,options:{productReference?:string}={}):PimEvidenceCatalog{
 const records=candidates.flatMap(candidate=>candidate.evidence.map(evidence=>({attribute:candidate.attribute,evidence}))).sort((a,b)=>`${a.attribute}|${a.evidence.sourceType}|${a.evidence.sourceReference}|${a.evidence.normalizedValue}`.localeCompare(`${b.attribute}|${b.evidence.sourceType}|${b.evidence.sourceReference}|${b.evidence.normalizedValue}`)),byKey=new Map<string,typeof records[number]>();
 for(const record of records){const key=`${record.attribute}|${record.evidence.sourceType}|${record.evidence.sourceReference}|${normalizeMeasurement(record.evidence.normalizedValue||record.evidence.rawValue).toLocaleLowerCase("pt-BR")}`;if(!byKey.has(key))byKey.set(key,record);}
 const byId=new Map<string,PimEvidenceDescriptor>(),entries=[...byKey.values()].map((record,index)=>{const normalizedValue=normalizeMeasurement(record.evidence.normalizedValue||record.evidence.rawValue),entry={id:`e${index+1}`,attribute:record.attribute,value:normalizedValue,sourceType:record.evidence.sourceType,sourceReference:record.evidence.sourceReference};byId.set(entry.id,{entry,evidence:record.evidence,allowedAttributes:[record.attribute],normalizedValue,unit:detectUnit(normalizedValue),compound:/\s[xX]\s/.test(normalizedValue)});return entry;});return{entries,byId,productReference:options.productReference??null};
}

const equal=(left:string,right:string)=>normalizeMeasurement(left).toLocaleLowerCase("pt-BR")===normalizeMeasurement(right).toLocaleLowerCase("pt-BR");
const expanded=(modelValue:string,evidenceValue:string)=>{const model=normalizeMeasurement(modelValue).toLocaleLowerCase("pt-BR"),evidence=normalizeMeasurement(evidenceValue).toLocaleLowerCase("pt-BR");return model!==evidence&&model.includes(evidence)&&/[\/,-]/.test(model);};

export function auditCompactEvidenceBindings(output:PimCompactStructuredOutput,catalog:PimEvidenceCatalog,options:{expectedProductReference?:string}={}):EvidenceBindingFailure[]{const failures:EvidenceBindingFailure[]=[];for(const item of output.attributes)for(const ref of [...new Set(item.evidenceRefs)]){const match=catalog.byId.get(ref),base={ref,attribute:item.attribute,modelValue:item.value};if(!match){failures.push({code:"INVALID_EVIDENCE_REF",...base});continue;}if(options.expectedProductReference&&catalog.productReference&&options.expectedProductReference!==catalog.productReference){failures.push({code:"CROSS_PRODUCT_FOREIGN_REF",...base,evidenceAttribute:match.entry.attribute,evidenceValue:match.entry.value});continue;}if(!match.allowedAttributes.includes(item.attribute)){failures.push({code:"SAME_PRODUCT_SEMANTICALLY_FOREIGN_REF",...base,evidenceAttribute:match.entry.attribute,evidenceValue:match.entry.value});continue;}if(!equal(match.normalizedValue,item.value))failures.push({code:expanded(item.value,match.normalizedValue)?"UNSUPPORTED_VALUE_EXPANSION":"UNSUPPORTED_EVIDENCE_VALUE",...base,evidenceAttribute:match.entry.attribute,evidenceValue:match.entry.value});}return failures;}

export function resolveCompactEvidence(output:PimCompactStructuredOutput,catalog:PimEvidenceCatalog,options:{expectedProductReference?:string}={}):PimStructuredOutput{const failures=auditCompactEvidenceBindings(output,catalog,options);if(failures.length){const failure=failures[0],legacyCode=failure.code==="SAME_PRODUCT_SEMANTICALLY_FOREIGN_REF"?"FOREIGN_EVIDENCE_REF":failure.code==="UNSUPPORTED_EVIDENCE_VALUE"||failure.code==="UNSUPPORTED_VALUE_EXPANSION"?"SEMANTIC_EVIDENCE_MISMATCH":failure.code;throw new Error(`${legacyCode}:${failure.code}:${failure.ref}`);}const attributes=output.attributes.map(item=>{const refs=[...new Set(item.evidenceRefs)],resolved=refs.map(ref=>catalog.byId.get(ref)?.evidence).filter((value):value is PimEvidence=>Boolean(value)),confidence=Math.min(...resolved.map(item=>item.confidence));return{attribute:item.attribute,value:item.value,confidence,status:"CANDIDATE" as const,evidence:resolved,needsEvidence:false};});return{suggestedName:output.suggestedName,shortDescription:output.shortDescription,longDescription:output.longDescription,bulletPoints:output.bulletPoints,application:output.application,attributes,seo:output.seo,uncertainties:output.uncertainties,evidenceReferences:[...new Set(output.attributes.flatMap(item=>item.evidenceRefs))]};}
