import {z} from "zod";
import {PIM_ATTRIBUTE_CODES} from "./enrichment-types.ts";
import {auditSemanticUnit} from "./semantic-validation.ts";
export const PIM_LEGACY_SCHEMA_VERSION="pim-structured-output-v2";
export const PIM_LEGACY_OUTPUT_LIMITS={displayName:120,shortDescription:240,longDescription:900,bulletCount:6,bulletLength:160,application:300,attributeCount:12,attributeValue:300,evidencePerAttribute:3,evidenceText:300,seoTitle:70,metaDescription:160,searchTerms:10,searchTermLength:60,uncertainties:5,uncertaintyLength:180,evidenceReferences:20,evidenceReferenceLength:120} as const;
const PIM_OUTPUT_LIMITS=PIM_LEGACY_OUTPUT_LIMITS;

const evidence=z.object({sourceType:z.enum(["SOURCE_TITLE","SOURCE_DESCRIPTION","SOURCE_ATTRIBUTE","SOURCE_BRAND","SOURCE_CATEGORY","GTIN_REFERENCE","MANUFACTURER","MANUAL","AI_INFERENCE"]),sourceReference:z.string().min(1).max(PIM_OUTPUT_LIMITS.evidenceReferenceLength),rawValue:z.string().max(PIM_OUTPUT_LIMITS.evidenceText),normalizedValue:z.string().max(PIM_OUTPUT_LIMITS.evidenceText),confidence:z.number().min(0).max(1),extractionMethod:z.enum(["deterministic","structured_source","ai_inference"])}).strict();
const attribute=z.object({attribute:z.enum(PIM_ATTRIBUTE_CODES),value:z.string().min(1).max(PIM_OUTPUT_LIMITS.attributeValue),confidence:z.number().min(0).max(1),status:z.enum(["CANDIDATE","CONFLICT","NEEDS_REVIEW"]),evidence:z.array(evidence).min(1).max(PIM_OUTPUT_LIMITS.evidencePerAttribute),needsEvidence:z.boolean().default(false)}).strict().superRefine((value,context)=>{const mismatch=auditSemanticUnit(value.attribute,value.value);if(mismatch)context.addIssue({code:"custom",message:`${mismatch.code}:${mismatch.attribute}:${mismatch.unit}`,path:["value"]});});
export const pimStructuredOutputSchema=z.object({suggestedName:z.string().trim().min(1).max(PIM_OUTPUT_LIMITS.displayName).nullable(),shortDescription:z.string().trim().max(PIM_OUTPUT_LIMITS.shortDescription).nullable(),longDescription:z.string().trim().max(PIM_OUTPUT_LIMITS.longDescription).nullable(),bulletPoints:z.array(z.string().trim().min(1).max(PIM_OUTPUT_LIMITS.bulletLength)).max(PIM_OUTPUT_LIMITS.bulletCount),application:z.string().trim().max(PIM_OUTPUT_LIMITS.application).nullable(),attributes:z.array(attribute).max(PIM_OUTPUT_LIMITS.attributeCount),seo:z.object({title:z.string().trim().max(PIM_OUTPUT_LIMITS.seoTitle).nullable(),metaDescription:z.string().trim().max(PIM_OUTPUT_LIMITS.metaDescription).nullable(),searchTerms:z.array(z.string().trim().min(1).max(PIM_OUTPUT_LIMITS.searchTermLength)).max(PIM_OUTPUT_LIMITS.searchTerms)}).strict(),uncertainties:z.array(z.string().trim().min(1).max(PIM_OUTPUT_LIMITS.uncertaintyLength)).max(PIM_OUTPUT_LIMITS.uncertainties),evidenceReferences:z.array(z.string().trim().min(1).max(PIM_OUTPUT_LIMITS.evidenceReferenceLength)).max(PIM_OUTPUT_LIMITS.evidenceReferences)}).strict();
export {PIM_LEGACY_SCHEMA_VERSION as PIM_SCHEMA_VERSION};
export type PimStructuredOutput=z.infer<typeof pimStructuredOutputSchema>;
export function validatePimStructuredOutput(value:unknown){return pimStructuredOutputSchema.parse(value);}
