import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import { CartProvider } from "@/components/Cart/CartProvider";
import { Footer } from "@/components/Footer/Footer";
import { BackToTopButton } from "@/components/UI/BackToTopButton";
import { OverlayManagerProvider } from "@/context/OverlayManager";
import "./globals.css";
import { SITE_URL } from "@/lib/routing/storefrontUrls";
import { AccountProvider } from "@/hooks/useAccount";
import { FavoritesProvider } from "@/lib/favorites/favorites-context";

const PERSI_HEADER_COLOR = "#0c2d72";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: "Create Next App",
  description: "Generated by create next app",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Persi Materiais",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: PERSI_HEADER_COLOR,
  colorScheme: "light",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={`${inter.variable} h-full antialiased`}>
      <body className="flex min-h-full flex-col">
        <OverlayManagerProvider>
          <AccountProvider>
            <FavoritesProvider>
              <CartProvider>
                <div className="flex-1">{children}</div>
                <Footer />
                <BackToTopButton />
              </CartProvider>
            </FavoritesProvider>
          </AccountProvider>
        </OverlayManagerProvider>
      </body>
    </html>
  );
}
