import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import { CartProvider } from "@/components/Cart/CartProvider";
import { Footer } from "@/components/Footer/Footer";
import { BackToTopButton } from "@/components/UI/BackToTopButton";
import "./globals.css";

const PERSI_HEADER_COLOR = "#0c2d72";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Persi Materiais",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: PERSI_HEADER_COLOR,
  colorScheme: "light",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <body className="flex min-h-full flex-col">
        <CartProvider>
          <div className="flex-1">{children}</div>
          <Footer />
          <BackToTopButton />
        </CartProvider>
      </body>
    </html>
  );
}
