import { index, bigint, char, integer, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { products, productVariants } from "./catalog";
import { checkoutSessions } from "./checkout";
import { customerAddresses, customers, stores } from "./commerce";

export const orderStatus = pgEnum("order_status", ["pending", "confirmed", "cancelled", "completed"]);
export const orderAddressType = pgEnum("order_address_type", ["billing", "shipping"]);
export const orderAdjustmentType = pgEnum("order_adjustment_type", ["coupon", "promotion", "manual_discount", "payment_discount", "shipping_discount", "fee", "correction"]);
export const orderAdjustmentDirection = pgEnum("order_adjustment_direction", ["discount", "charge"]);
export const orderActorType = pgEnum("order_actor_type", ["system", "customer", "admin", "worker"]);

export const orders = pgTable("orders", {
  id: uuid().primaryKey().defaultRandom(), storeId: uuid("store_id").notNull().references(() => stores.id, { onDelete: "restrict" }),
  customerId: uuid("customer_id").references(() => customers.id, { onDelete: "set null" }), checkoutSessionId: uuid("checkout_session_id").references(() => checkoutSessions.id, { onDelete: "restrict" }),
  orderSequence: bigint("order_sequence", { mode: "bigint" }).notNull(), orderNumber: text("order_number").notNull(), status: orderStatus().notNull().default("pending"), currency: char({ length: 3 }).notNull(),
  itemsSubtotalMinor: bigint("items_subtotal_minor", { mode: "bigint" }).notNull(), discountTotalMinor: bigint("discount_total_minor", { mode: "bigint" }).notNull().default(BigInt(0)),
  shippingTotalMinor: bigint("shipping_total_minor", { mode: "bigint" }).notNull().default(BigInt(0)), taxTotalMinor: bigint("tax_total_minor", { mode: "bigint" }).notNull().default(BigInt(0)),
  feeTotalMinor: bigint("fee_total_minor", { mode: "bigint" }).notNull().default(BigInt(0)), grandTotalMinor: bigint("grand_total_minor", { mode: "bigint" }).notNull(),
  contactName: text("contact_name").notNull(), contactEmail: text("contact_email").notNull(), contactPhone: text("contact_phone"), taxIdType: text("tax_id_type"),
  taxIdCiphertext: text("tax_id_ciphertext"), taxIdFingerprint: text("tax_id_fingerprint"), taxIdMasked: text("tax_id_masked"), submissionRequestHash: text("submission_request_hash"), correlationId: uuid("correlation_id").notNull().defaultRandom(),
  version: bigint({ mode: "bigint" }).notNull().default(BigInt(0)), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(), cancelledAt: timestamp("cancelled_at", { withTimezone: true }), completedAt: timestamp("completed_at", { withTimezone: true }),
}, (table) => [uniqueIndex("orders_checkout_session_id_key").on(table.checkoutSessionId), uniqueIndex("orders_store_sequence_unique").on(table.storeId, table.orderSequence), uniqueIndex("orders_store_number_unique").on(table.storeId, table.orderNumber), uniqueIndex("orders_correlation_id_key").on(table.correlationId), index("orders_customer_store_idx").on(table.customerId, table.storeId, table.createdAt, table.id), index("orders_store_status_idx").on(table.storeId, table.status, table.createdAt, table.id)]);

export const orderItems = pgTable("order_items", { id: uuid().primaryKey().defaultRandom(), orderId: uuid("order_id").notNull().references(() => orders.id, { onDelete: "restrict" }), lineNumber: integer("line_number").notNull(), productId: uuid("product_id").references(() => products.id, { onDelete: "restrict" }), productVariantId: uuid("product_variant_id").references(() => productVariants.id, { onDelete: "restrict" }), skuSnapshot: text("sku_snapshot").notNull(), gtinSnapshot: text("gtin_snapshot"), productNameSnapshot: text("product_name_snapshot").notNull(), variantLabelSnapshot: text("variant_label_snapshot"), quantity: bigint({ mode: "bigint" }).notNull(), unitRegularAmountMinor: bigint("unit_regular_amount_minor", { mode: "bigint" }).notNull(), unitEffectiveAmountMinor: bigint("unit_effective_amount_minor", { mode: "bigint" }).notNull(), lineSubtotalMinor: bigint("line_subtotal_minor", { mode: "bigint" }).notNull(), lineDiscountMinor: bigint("line_discount_minor", { mode: "bigint" }).notNull().default(BigInt(0)), lineTaxMinor: bigint("line_tax_minor", { mode: "bigint" }).notNull().default(BigInt(0)), lineTotalMinor: bigint("line_total_minor", { mode: "bigint" }).notNull(), currency: char({ length: 3 }).notNull(), sourceFingerprint: text("source_fingerprint").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("order_items_line_unique").on(table.orderId, table.lineNumber), index("order_items_order_idx").on(table.orderId, table.lineNumber, table.id)]);
export const orderAddresses = pgTable("order_addresses", { id: uuid().primaryKey().defaultRandom(), orderId: uuid("order_id").notNull().references(() => orders.id, { onDelete: "restrict" }), addressType: orderAddressType("address_type").notNull(), sourceCustomerAddressId: uuid("source_customer_address_id").references(() => customerAddresses.id, { onDelete: "set null" }), recipient: text().notNull(), company: text(), street: text().notNull(), number: text().notNull(), complement: text(), neighborhood: text().notNull(), city: text().notNull(), state: char({ length: 2 }).notNull(), postalCode: text("postal_code").notNull(), country: char({ length: 2 }).notNull().default("BR"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("order_addresses_type_unique").on(table.orderId, table.addressType), index("order_addresses_order_idx").on(table.orderId, table.addressType, table.id)]);
export const orderAdjustments = pgTable("order_adjustments", { id: uuid().primaryKey().defaultRandom(), orderId: uuid("order_id").notNull().references(() => orders.id, { onDelete: "restrict" }), orderItemId: uuid("order_item_id").references(() => orderItems.id, { onDelete: "restrict" }), adjustmentType: orderAdjustmentType("adjustment_type").notNull(), direction: orderAdjustmentDirection().notNull(), amountMinor: bigint("amount_minor", { mode: "bigint" }).notNull(), currency: char({ length: 3 }).notNull(), codeSnapshot: text("code_snapshot"), descriptionSnapshot: text("description_snapshot").notNull(), reversesAdjustmentId: uuid("reverses_adjustment_id"), correlationId: uuid("correlation_id").notNull().defaultRandom(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("order_adjustments_reversal_unique").on(table.reversesAdjustmentId), index("order_adjustments_order_idx").on(table.orderId, table.createdAt, table.id)]);
export const orderStatusEvents = pgTable("order_status_events", { id: uuid().primaryKey().defaultRandom(), orderId: uuid("order_id").notNull().references(() => orders.id, { onDelete: "restrict" }), fromStatus: orderStatus("from_status"), toStatus: orderStatus("to_status").notNull(), actorType: orderActorType("actor_type").notNull(), actorId: text("actor_id"), reasonCode: text("reason_code"), reason: text(), correlationId: uuid("correlation_id").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("order_status_events_correlation_unique").on(table.orderId, table.correlationId), index("order_status_events_order_idx").on(table.orderId, table.createdAt, table.id)]);

export type NativeOrderRow = typeof orders.$inferSelect;
