import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dirname, "..");
const read = (path) => readFileSync(join(root, path), "utf8");
const sync = read("src/Catalog/GtinSync.php");
const client = read("src/Api/OlistClient.php");
const admin = read("src/Admin/AdminPage.php");
const batch = read("src/Catalog/BatchProcessor.php");
const activator = read("src/Activator.php");
const discovery = read("src/Attributes/AttributeDiscovery.php");
const titleExtractor = read("src/Attributes/TitleAttributeExtractor.php");
const compositeParser = read("src/Attributes/CompositeDimensionParser.php");
const descriptionExtractor = read("src/Attributes/DescriptionAttributeExtractor.php");
const normalization = read("src/Attributes/NormalizationService.php");
const families = read("src/Attributes/ProductFamilyContext.php");
const termResolver = read("src/Attributes/WooAttributeTermResolver.php");
const destinationResolver = read("src/Attributes/AttributeDestinationResolver.php");
const diagnostic = read("src/Admin/OlistDiagnosticPage.php");
const sanitizer = read("src/Support/PayloadSanitizer.php");
const attributesPage = read("src/Admin/AttributesPage.php");
const runItems = read("src/Infrastructure/RunItemRepository.php");
const snapshot = read("src/Infrastructure/OlistSnapshotRepository.php");
const performance = read("src/Support/Performance.php");
const workerLock = read("src/Support/WorkerLock.php");
const manualQueue = read("src/Catalog/ManualQueueBuilder.php");
const productSearch = read("src/Admin/ProductSearch.php");

assert.match(sync, /set_global_unique_id/);
assert.doesNotMatch(sync, /set_sku|set_price|set_stock|update_post_meta/);
assert.match(sync, /'dry-run' === \$run->mode|\$dry_run/);
assert.match(client, /\/produtos/);
assert.match(client, /'codigo' => \$sku/);
assert.match(client, /Authorization.*Bearer/);
assert.doesNotMatch(client, /client_secret\s*=\s*['"][^'"]+['"]/i);
assert.match(admin, /manage_woocommerce/);
assert.match(admin, /confirm_sync/);
assert.doesNotMatch(admin, /'SINCRONIZAR' !==/);
assert.match(admin, /wp_ajax_persi_catalog_product_search/);
assert.match(admin, /wp_ajax_persi_catalog_selection_preview/);
assert.match(admin, /check_ajax_referer\( 'persi_catalog_product_selection'/);
assert.match(batch, /'selected' === \$scope/);
assert.match(batch, /in_array\( 'attributes', \$modules, true \).*! in_array\( 'gtin', \$modules, true \).*\$scope = 'all'/);
assert.match(batch, /\$item_modules/);
assert.match(runItems, /\$item\['modules'\]/);
assert.match(manualQueue, /get_post_type/);
assert.match(manualQueue, /get_post_status/);
assert.match(manualQueue, /get_children/);
assert.match(manualQueue, /'attributes'/);
assert.match(manualQueue, /'gtin'/);
assert.match(productSearch, /LIMIT %d OFFSET %d/);
assert.match(productSearch, /wc_product_meta_lookup/);
assert.doesNotMatch(productSearch, /OlistClient|wp_remote_/);
assert.match(runItems, /INSERT INTO.*VALUES/);
assert.doesNotMatch(runItems, /foreach[\s\S]*\$wpdb->(?:insert|replace)/);
assert.match(snapshot, /expires_at/);
assert.match(performance, /hrtime\( true \)/);
assert.match(batch, /worker_budget_seconds/);
assert.match(batch, /olist_circuit_open/);
assert.match(batch, /SELECT posts\.ID, posts\.post_parent, posts\.post_type/);
assert.match(admin, /check_admin_referer/);
assert.match(batch, /as_schedule_single_action/);
assert.match(batch, /as_enqueue_async_action\( self::ACTION, array\( \$run_id \), self::GROUP, false \)/);
assert.match(batch, /retry_after[\s\S]*self::GROUP, false/);
assert.match(batch, /lookup\.global_unique_id IS NULL/);
assert.match(batch, /previous_empty\.status = 'OLIST_NO_GTIN'/);
assert.match(batch, /prepare_queue/);
assert.match(batch, /persi_catalog_run_items/);
assert.doesNotMatch(batch, /save_post_product|woocommerce_update_product/);
assert.match(batch, /persi_catalog_run_items/);
assert.match(batch, /product_variation/);
assert.doesNotMatch(read("src/Plugin.php"), /ProductBulkActions/);
assert.match(activator, /modules varchar\(191\).*'gtin'/);
assert.match(activator, /persi_catalog_attribute_candidates/);
assert.match(activator, /persi_catalog_attribute_mappings/);
assert.match(diagnostic, /check_admin_referer/);
assert.match(diagnostic, /manage_woocommerce/);
assert.match(diagnostic, /product_detail/);
assert.match(sanitizer, /access_token.*refresh_token.*client_secret.*authorization.*cookie/);
assert.match(discovery, /OLIST_STRUCTURED/);
assert.match(discovery, /WOO_EXISTING/);
assert.match(titleExtractor, /TITLE_PATTERN/);
assert.match(descriptionExtractor, /DESCRIPTION_LABEL_VALUE/);
assert.match(normalization, /mm²/);
assert.match(families, /electrical_wire_cable/);
assert.match(families, /hydraulic_pipe/);
assert.match(termResolver, /get_terms/);
assert.match(termResolver, /ATTRIBUTE_TERM_MATCHED|AttributeStatuses::TERM_MATCHED/);
assert.match(activator, /DATABASE_VERSION = '10'/);
assert.match(activator, /display_value text/);
assert.match(activator, /components longtext/);
assert.match(activator, /search_aliases longtext/);
assert.match(activator, /persi_catalog_attribute_aliases/);
assert.match(titleExtractor, /potencia_aparente/);
assert.match(titleExtractor, /secao_condutor/);
assert.match(normalization, /kVA/);
assert.match(normalization, /Monofásica/);
assert.match(destinationResolver, /pa_bitola-em-milimetros/);
assert.match(destinationResolver, /pa_bitola/);
assert.match(destinationResolver, /pa_medida/);
assert.match(compositeParser, /medida_composta/);
assert.match(compositeParser, /COMPOSITE_UNIT_PROPAGATION/);
assert.match(compositeParser, /COMPOSITE_CONTEXT_INFERENCE/);
assert.match(compositeParser, /COMPOSITE_CONSUMES_COMPONENTS/);
assert.match(titleExtractor, /without_consumed_spans/);
assert.doesNotMatch(compositeParser, /'attribute_key' => 'bitola'/);
assert.match(compositeParser, /hydraulic_fitting/);
assert.doesNotMatch(compositeParser, /wp_set_object_terms|wp_insert_term|wc_create_attribute|set_attributes|update_post_meta/);
assert.match(client, /OLIST_HTTP_429/);
assert.match(client, /OLIST_TOKEN_REFRESH_FAILED/);
assert.match(client, /OLIST_INVALID_JSON/);
assert.match(client, /backoff/);
assert.match(read("src/Api/TokenStore.php"), /expire_access/);
assert.doesNotMatch(client, /tokens->clear/);
assert.match(batch, /partial_success/);
assert.match(read("src/Infrastructure/RunRepository.php"), /PARTIAL_SUCCESS/);
assert.match(titleExtractor, /inch_dimension_pattern/);
assert.match(titleExtractor, /plate_thickness_pattern/);
assert.match(read("src/Infrastructure/AttributeCandidateRepository.php"), /hide_rejected/);
assert.match(discovery, /AttributeStatuses::REVIEW_REQUIRED/);
assert.doesNotMatch(discovery, /wp_set_object_terms|wc_create_attribute|set_attributes|save\s*\(/);
assert.doesNotMatch(attributesPage, /wp_set_object_terms|wc_create_attribute|set_attributes/);
assert.doesNotMatch(`${discovery}\n${titleExtractor}\n${descriptionExtractor}`, /wp_set_object_terms|wc_create_attribute|set_attributes|update_post_meta/);
assert.doesNotMatch(termResolver, /wp_insert_term|wp_set_object_terms|wc_create_attribute/);
assert.match(admin, /wp_ajax_persi_catalog_progress/);
assert.match(admin, /wp_ajax_persi_catalog_cancel/);
assert.match(admin, /wp_ajax_persi_catalog_kick_worker/);
assert.match(admin, /check_ajax_referer\( 'persi_catalog_cancel'/);
assert.match(admin, /as_unschedule_all_actions/);
assert.match(batch, /is_cancelled\( \$run_id \)/);
assert.match(batch, /new WorkerLock/);
assert.match(batch, /\$run->total_items - \(int\) \$run->processed/);
assert.doesNotMatch(read("src/Infrastructure/RunRepository.php"), /'requested_limit'\s*=>\s*\$total/);
assert.match(workerLock, /add_option/);
assert.match(workerLock, /persi_catalog_worker_lock_/);
assert.match(admin, /check_ajax_referer\( 'persi_catalog_progress'/);
assert.match(admin, /manage_woocommerce/);

console.log("PASS estrutura e limites de responsabilidade");
