"use client";
import {useActionState} from "react";
import {runEditorialWorkflow,saveEditorialDraft,type PimActionState} from "@/app/admin/products/[id]/actions";
import type {PimEditorialContent,PimStatus} from "@/lib/pim/repository";

const initialState:PimActionState={ok:false},fieldClass="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2";
const editableFields=["commercialName","shortDescription","description","application","seoTitle","metaDescription"] as const;
const labels:Record<(typeof editableFields)[number],string>={commercialName:"Nome comercial",shortDescription:"Descrição curta",description:"Descrição completa",application:"Aplicação",seoTitle:"Título de SEO",metaDescription:"Meta description"};
const value=(content:Partial<PimEditorialContent>|null,key:keyof PimEditorialContent)=>{const current=content?.[key];return Array.isArray(current)?current.join("\n"):current??"";};
function ReadColumn({title,content,fallback}:{title:string;content:PimEditorialContent|null;fallback?:Partial<PimEditorialContent>}){return <section className="rounded-lg border bg-background-soft p-4"><h3 className="font-bold text-heading">{title}</h3><dl className="mt-3 space-y-3 text-sm">{editableFields.map(key=><div key={key}><dt className="font-semibold text-muted">{labels[key]}</dt><dd className="whitespace-pre-wrap">{value(content,key)||value(fallback??null,key)||"—"}</dd></div>)}</dl></section>;}

export function PimEditorialEditor({productId,version,status,source,draft,approved}:{productId:string;version:string;status:PimStatus;source:Partial<PimEditorialContent>;draft:PimEditorialContent;approved:PimEditorialContent|null}){
 const [saveState,saveAction,savePending]=useActionState(saveEditorialDraft,initialState),[workflowState,workflowAction,workflowPending]=useActionState(runEditorialWorkflow,initialState);
 const editable=["raw","normalized","needs_enrichment","draft","ai_suggested"].includes(status);
 const actions=status==="draft"?[["SUBMIT_REVIEW","Enviar para revisão"],["DISCARD_DRAFT","Descartar alterações"]]:status==="needs_review"?[["APPROVE","Aprovar no PIM"],["REJECT","Rejeitar revisão"]]:status==="approved"||status==="rejected"?[["REOPEN","Criar nova edição"]]:[];
 return <div className="mt-4 space-y-4"><div className="grid gap-4 xl:grid-cols-3"><ReadColumn title="ATUAL" content={null} fallback={source}/><form action={saveAction} className="rounded-lg border border-blue-200 bg-white p-4"><h3 className="font-bold text-heading">DRAFT</h3><input type="hidden" name="productId" value={productId}/><input type="hidden" name="version" value={version}/><input type="hidden" name="bulletPoints" value={draft.bulletPoints.join("\n")}/><input type="hidden" name="specifications" value={draft.specifications??""}/><input type="hidden" name="searchTerms" value={draft.searchTerms.join("\n")}/><input type="hidden" name="imageAltText" value={draft.imageAltText??""}/><div className="mt-3 space-y-3">{editableFields.map(key=>{const changed=value(draft,key)!==value((approved??source),key),multiline=key!=="commercialName"&&key!=="seoTitle";return <label key={key} className="block text-sm font-semibold">{labels[key]} {changed&&<span className="ml-1 text-xs text-secondary">Alterado</span>}{multiline?<textarea name={key} defaultValue={value(draft,key)} disabled={!editable} rows={key==="description"?6:3} className={fieldClass}/>:<input name={key} defaultValue={value(draft,key)} disabled={!editable} className={fieldClass}/>}</label>;})}</div>{editable&&<button disabled={savePending} className="mt-4 rounded-lg bg-primary px-4 py-2 font-semibold text-white disabled:opacity-60">{savePending?"Salvando…":"Salvar rascunho"}</button>}{saveState.error&&<p role="alert" className="mt-3 text-sm text-red-700">{saveState.error}</p>}{saveState.ok&&<p role="status" className="mt-3 text-sm text-emerald-700">Rascunho salvo.</p>}</form><ReadColumn title="APROVADO NO PIM" content={approved}/></div>
 {actions.length>0&&<form action={workflowAction} className="rounded-lg border bg-white p-4"><input type="hidden" name="productId" value={productId}/><input type="hidden" name="version" value={version}/><label className="block text-sm font-semibold">Motivo (opcional)<input name="reason" maxLength={1000} className={fieldClass}/></label><div className="mt-3 flex flex-wrap gap-2">{actions.map(([action,label])=><button key={action} name="action" value={action} disabled={workflowPending} className="rounded-lg border border-primary px-4 py-2 font-semibold text-primary disabled:opacity-60">{label}</button>)}</div>{workflowState.error&&<p role="alert" className="mt-3 text-sm text-red-700">{workflowState.error}</p>}{workflowState.ok&&<p role="status" className="mt-3 text-sm text-emerald-700">Etapa atualizada com sucesso.</p>}<p className="mt-3 text-xs text-muted">A aprovação é interna ao PIM. A publicação no site permanece desabilitada.</p></form>}
 </div>;
}
