import crypto from "node:crypto";
import fs from "node:fs";
import postgres from "postgres";
import { readPrivateEnvironment, stagingDirectUrl, STAGING_PROJECT_REF } from "./config.mjs";
import { WooReadOnlyExtractor } from "./extract.mjs";
import { CatalogImporter } from "./import.mjs";
import { ATTRIBUTE_RULES, resolveGtin, slugify } from "./normalize.mjs";
import { mapSellableItems } from "./map.mjs";
import { createCheckpoint, databaseThreshold, loadCheckpoint, pendingExternalIds, recordCheckpoint, saveCheckpoint, shouldAbortFailure } from "./checkpoint.mjs";

const TOTAL=3080,CHECKPOINT_SIZE=50,CHECKPOINT_PATH="supabase/.temp/catalog-import/full-import-checkpoint.json",RESULT_PATH="supabase/.temp/catalog-import/full-import-result.json";
if(!process.argv.includes("--staging")||!process.argv.includes("--approved-full-import"))throw new Error("Exige --staging --approved-full-import.");
if(STAGING_PROJECT_REF!=="vtrujmhhkmvjzfklzxip")throw new Error("TARGET_NOT_APPROVED");
const resume=process.argv.includes("--resume"),elapsed=(start)=>Math.round(performance.now()-start),percentile=(values,p)=>values.length?values[Math.min(values.length-1,Math.ceil(values.length*p)-1)]:0;
const snapshot=(value)=>JSON.parse(JSON.stringify(value)),metricDelta=(after,before)=>Object.fromEntries(["insert","update","delete","noop"].map((key)=>[key,after[key]-before[key]]));

async function databaseSnapshot(sql){
  const [row]=await sql`select current_database() database,pg_database_size(current_database())::bigint bytes,
    (select count(*) from public.products)::int products,(select count(*) from public.product_variants)::int variants,
    (select count(*) from public.brands)::int brands,(select count(*) from public.categories)::int categories,
    (select count(*) from public.media_assets)::int media_assets,(select count(*) from public.product_media)::int product_media,
    (select count(*) from public.attributes)::int attributes,(select count(*) from public.attribute_values)::int attribute_values,
    (select count(*) from public.product_attribute_values)::int assignments,(select count(*) from public.prices)::int prices,
    (select count(*) from public.inventory_levels)::int inventory_levels,(select count(*) from public.inventory_movements)::int inventory_movements,
    (select count(*) from public.external_mappings)::int external_mappings`;
  return{...row,bytes:String(row.bytes)};
}
async function baselineMappings(sql,externalIds){return sql`select entity_type,external_id,internal_id::text internal_id from public.external_mappings where system='woocommerce' and entity_type in ('product','product_variant') and external_id in ${sql(externalIds.map(String))} order by entity_type,external_id`;}
function duplicateGtins(products){const seen=new Set(),duplicates=new Set();for(const product of products){const value=resolveGtin(product).value;if(!value)continue;if(seen.has(value))duplicates.add(value);else seen.add(value);}return duplicates;}
function expectedPim(source){return(source.attributes??[]).filter((attribute)=>{const rule=ATTRIBUTE_RULES.get(String(attribute.slug??"").toLowerCase());return rule&&rule.entity!=="brand";}).reduce((sum,attribute)=>sum+(attribute.options?.length??0),0);}

async function reconcile(sql,sources,duplicateSet){
  const productRows=await sql`select m.external_id,p.id::text product_id,p.name,p.slug,p.status,p.primary_category_id::text primary_category_id,v.id::text variant_id,v.sku_normalized,v.gtin,pr.list_amount_minor::text regular,pr.sale_amount_minor::text sale,pr.sale_valid_from,pr.sale_valid_to,il.quantity_on_hand::text stock
    from public.external_mappings m join public.products p on p.id=m.internal_id left join public.product_variants v on v.product_id=p.id left join public.prices pr on pr.product_variant_id=v.id and pr.status='active' left join public.inventory_levels il on il.product_variant_id=v.id
    where m.system='woocommerce' and m.entity_type='product'`;
  const categories=await sql`select pm.external_id product_external,array_agg(cm.external_id order by cm.external_id) ids from public.external_mappings pm join public.product_categories pc on pc.product_id=pm.internal_id join public.external_mappings cm on cm.internal_id=pc.category_id and cm.system='woocommerce' and cm.entity_type='category' where pm.system='woocommerce' and pm.entity_type='product' group by pm.external_id`;
  const media=await sql`select pmapping.external_id product_external,array_agg(mmapping.external_id order by rel.sort_order) ids from public.external_mappings pmapping join public.product_media rel on rel.product_id=pmapping.internal_id join public.external_mappings mmapping on mmapping.internal_id=rel.media_asset_id and mmapping.system='woocommerce' and mmapping.entity_type='media_asset' where pmapping.system='woocommerce' and pmapping.entity_type='product' group by pmapping.external_id`;
  const pim=await sql`select pm.external_id product_external,count(*)::int count from public.external_mappings pm join public.product_attribute_values pav on pav.product_id=pm.internal_id where pm.system='woocommerce' and pm.entity_type='product' group by pm.external_id`;
  const target=new Map(productRows.map((row)=>[row.external_id,row])),categoryMap=new Map(categories.map((row)=>[row.product_external,row.ids.map(String)])),mediaMap=new Map(media.map((row)=>[row.product_external,row.ids.map(String)])),pimMap=new Map(pim.map((row)=>[row.product_external,row.count]));
  const differences=[];
  for(const source of sources){const item=mapSellableItems(source,[],{duplicateGtins:duplicateSet})[0],row=target.get(String(source.id));if(!row){differences.push({wooId:source.id,fields:["missing_product"]});continue;}
    const expected={name:source.name,slug:slugify(source.slug||source.name),status:source.status==="publish"?"active":"draft",primary:null,sku:item.skuNormalized,gtin:item.gtin,regular:item.regularAmountMinor===null?null:String(item.regularAmountMinor),sale:item.saleAmountMinor===null?null:String(item.saleAmountMinor),saleFrom:item.salePeriod.from,saleTo:item.salePeriod.to,stock:String(item.stockQuantity),categories:(source.categories??[]).map((x)=>String(x.id)).sort(),media:(source.images??[]).map((x)=>String(x.id)),pim:expectedPim(source)};
    const actual={name:row.name,slug:row.slug,status:row.status,primary:row.primary_category_id,sku:row.sku_normalized,gtin:row.gtin,regular:row.regular,sale:row.sale,saleFrom:row.sale_valid_from?new Date(row.sale_valid_from).toISOString():null,saleTo:row.sale_valid_to?new Date(row.sale_valid_to).toISOString():null,stock:row.stock,categories:categoryMap.get(String(source.id))??[],media:mediaMap.get(String(source.id))??[],pim:pimMap.get(String(source.id))??0};
    const fields=Object.keys(expected).filter((key)=>JSON.stringify(expected[key])!==JSON.stringify(actual[key]));if(fields.length)differences.push({wooId:source.id,sku:item.skuNormalized,fields});
  }
  return{checked:sources.length,criticalDifferences:differences.length,fieldDifferences:differences.reduce((n,x)=>n+x.fields.length,0),differences:differences.slice(0,100)};
}
async function integrityAudit(sql){
  const [row]=await sql`select
    (select count(*) from public.product_variants v left join public.products p on p.id=v.product_id where p.id is null)::int orphan_variants,
    (select count(*) from public.prices x left join public.product_variants v on v.id=x.product_variant_id where v.id is null)::int orphan_prices,
    (select count(*) from public.inventory_levels x left join public.product_variants v on v.id=x.product_variant_id where v.id is null)::int orphan_inventory,
    (select count(*) from public.external_mappings m left join public.products p on m.entity_type='product' and p.id=m.internal_id left join public.product_variants v on m.entity_type='product_variant' and v.id=m.internal_id where m.entity_type in ('product','product_variant') and coalesce(p.id,v.id) is null)::int orphan_mappings,
    (select count(*) from public.product_media pm left join public.products p on p.id=pm.product_id left join public.media_assets ma on ma.id=pm.media_asset_id where p.id is null or ma.id is null)::int orphan_media,
    (select count(*) from public.product_attribute_values pav left join public.products p on p.id=pav.product_id left join public.attribute_values av on av.id=pav.attribute_value_id where p.id is null or av.id is null)::int orphan_pim,
    (select count(*) from (select entity_type,external_id from public.external_mappings where system='woocommerce' group by entity_type,external_id having count(*)>1)x)::int duplicate_mappings,
    (select count(*) from (select sku_normalized from public.product_variants group by sku_normalized having count(*)>1)x)::int duplicate_skus,
    (select count(*) from (select gtin from public.product_variants where gtin is not null group by gtin having count(*)>1)x)::int duplicate_gtins,
    (select count(*) from (select product_variant_id,price_list_id from public.prices where status='active' group by product_variant_id,price_list_id having count(*)>1)x)::int duplicate_prices,
    (select count(*) from (select product_id,category_id from public.product_categories group by product_id,category_id having count(*)>1)x)::int duplicate_categories,
    (select count(*) from (select product_id,media_asset_id,role,sort_order from public.product_media group by product_id,media_asset_id,role,sort_order having count(*)>1)x)::int duplicate_media`;
  return row;
}

const env=readPrivateEnvironment(),extractor=new WooReadOnlyExtractor(env),sql=postgres(stagingDirectUrl(env.stagingPassword),{max:1,prepare:false,ssl:"require",connect_timeout:15});
try{
  const [targetCheck]=await sql`select current_database() database,(select count(*) from supabase_migrations.schema_migrations)::int migrations`;
  if(targetCheck.database!=="postgres"||targetCheck.migrations!==7)throw new Error(`TARGET_OR_MIGRATION_MISMATCH:${targetCheck.database}:${targetCheck.migrations}`);
  const extractionStart=performance.now(),[sources,categories,brands]=await Promise.all([extractor.all("products"),extractor.all("products/categories"),extractor.all("products/brands")]),extractionMs=elapsed(extractionStart);
  if(sources.length!==TOTAL||sources.some((x)=>x.type!=="simple"))throw new Error(`SOURCE_GATE_FAILED:${sources.length}`);
  const duplicateSet=duplicateGtins(sources),approvedIds=JSON.parse(fs.readFileSync("supabase/.temp/catalog-import/gate-100.json","utf8")).selected,resumedCheckpoint=resume?loadCheckpoint(CHECKPOINT_PATH):null,currentBefore=await databaseSnapshot(sql),baseline=resumedCheckpoint?.baseline??currentBefore,beforeMappings=await baselineMappings(sql,approvedIds),baselineProducts=beforeMappings.filter((x)=>x.entity_type==="product"),baselineVariants=beforeMappings.filter((x)=>x.entity_type==="product_variant");
  if((!resume&&(baseline.products!==100||baseline.variants!==100))||baselineProducts.length!==100||baselineVariants.length!==100)throw new Error("BASELINE_100_MISMATCH");
  let checkpoint;if(resume){checkpoint=resumedCheckpoint;if(checkpoint.sourceCount!==TOTAL||checkpoint.target!==`persi-staging:${STAGING_PROJECT_REF}`)throw new Error("CHECKPOINT_TARGET_MISMATCH");const retryIds=new Set(checkpoint.failures.filter((x)=>x.classification==="record").map((x)=>x.externalId));checkpoint={...checkpoint,processed:checkpoint.processed-retryIds.size,failed:checkpoint.failed-retryIds.size,completedExternalIds:checkpoint.completedExternalIds.filter((id)=>!retryIds.has(id)),failures:checkpoint.failures.filter((x)=>!retryIds.has(x.externalId)),updatedAt:new Date().toISOString()};saveCheckpoint(CHECKPOINT_PATH,checkpoint);}else{checkpoint={...createCheckpoint({source:"WooCommerce READ ONLY",target:`persi-staging:${STAGING_PROJECT_REF}`,total:TOTAL}),runId:`catalog-full-${new Date().toISOString().replace(/[-:.TZ]/g,"")}-${crypto.randomUUID()}`,sourceCount:TOTAL,schemaMigrations:targetCheck.migrations,etlVersion:"E.6",checkpointSize:CHECKPOINT_SIZE,baseline};saveCheckpoint(CHECKPOINT_PATH,checkpoint);}
  const previousActiveMs=checkpoint.activeImportMs??Math.max(0,new Date(checkpoint.updatedAt).valueOf()-new Date(checkpoint.startedAt).valueOf()),pending=new Set(pendingExternalIds(checkpoint,sources.map((x)=>x.id))),importer=new CatalogImporter(sql,{categories,brands,profiling:true,duplicateGtins:duplicateSet}),durations=[],completedSinceCheckpoint=[],firstStart=performance.now();
  for(const [index,product]of sources.entries()){if(!pending.has(String(product.id)))continue;const before=snapshot(importer.metrics),started=performance.now();try{const result=await importer.importProduct(product),delta=metricDelta(importer.metrics,before),status=result.status==="conflict"?"conflicts":result.created?"imported":delta.insert||delta.update||delta.delete?"updated":"noop";checkpoint=recordCheckpoint(checkpoint,{externalId:product.id,page:Math.floor(index/100)+1,status});}catch(error){checkpoint=recordCheckpoint(checkpoint,{externalId:product.id,page:Math.floor(index/100)+1,status:"failed",error});saveCheckpoint(CHECKPOINT_PATH,checkpoint);if(shouldAbortFailure(error))throw error;}durations.push(elapsed(started));
    completedSinceCheckpoint.push(product);if(completedSinceCheckpoint.length===CHECKPOINT_SIZE||checkpoint.processed===TOTAL){const current=await databaseSnapshot(sql),threshold=databaseThreshold(current.bytes),batchReconciliation=await reconcile(sql,completedSinceCheckpoint,duplicateSet);checkpoint={...checkpoint,currentDatabaseSize:current.bytes,databaseThreshold:threshold,activeImportMs:previousActiveMs+elapsed(firstStart),lastBatchReconciliation:{checked:batchReconciliation.checked,criticalDifferences:batchReconciliation.criticalDifferences,fieldDifferences:batchReconciliation.fieldDifferences},updatedAt:new Date().toISOString()};saveCheckpoint(CHECKPOINT_PATH,checkpoint);console.log(`[${checkpoint.processed}/${TOTAL}] ${(checkpoint.processed/TOTAL*100).toFixed(1)}% | new=${checkpoint.imported} | update=${checkpoint.updated} | noop=${checkpoint.noop} | failed=${checkpoint.failed} | DB=${(Number(current.bytes)/1048576).toFixed(1)}MiB`);if(batchReconciliation.criticalDifferences)throw new Error("CHECKPOINT_RECONCILIATION_FAILED");if(threshold==="stop")throw new Error("DATABASE_SIZE_STOP");completedSinceCheckpoint.length=0;}
  }
  const firstMs=previousActiveMs+elapsed(firstStart),afterFirst=await databaseSnapshot(sql),firstReconciliation=await reconcile(sql,sources,duplicateSet),afterMappings=await baselineMappings(sql,approvedIds),afterMap=new Map(afterMappings.map((x)=>[`${x.entity_type}:${x.external_id}`,x.internal_id])),preserved=[...beforeMappings].filter((x)=>afterMap.get(`${x.entity_type}:${x.external_id}`)===x.internal_id).length;
  if(checkpoint.processed!==TOTAL||checkpoint.failed||checkpoint.conflicts||firstReconciliation.criticalDifferences||preserved!==beforeMappings.length)throw new Error("FIRST_PASS_GATE_FAILED");
  const secondImporter=new CatalogImporter(sql,{categories,brands,profiling:true,duplicateGtins:duplicateSet}),secondStart=performance.now();for(const [index,product]of sources.entries()){await secondImporter.importProduct(product);if((index+1)%CHECKPOINT_SIZE===0||index+1===TOTAL)console.log(`[idempotency ${index+1}/${TOTAL}]`);}const secondMs=elapsed(secondStart),afterSecond=await databaseSnapshot(sql),secondReconciliation=await reconcile(sql,sources,duplicateSet),audit=await integrityAudit(sql),secondMetrics=snapshot(secondImporter.metrics),sorted=[...durations].sort((a,b)=>a-b),profiles=[...importer.profiles].sort((a,b)=>b.totalMs-a.totalMs),preflight=JSON.parse(fs.readFileSync("supabase/.temp/catalog-import/full-preflight.json","utf8"));
  const result={run:{runId:checkpoint.runId,startedAt:checkpoint.startedAt,finishedAt:new Date().toISOString(),checkpoints:Math.ceil(TOTAL/CHECKPOINT_SIZE),checkpoint,resumed:resume},source:{products:sources.length,categories:categories.length,brands:brands.length,mediaReferences:sources.reduce((n,x)=>n+(x.images?.length??0),0),productsWithoutImage:sources.filter((x)=>!(x.images?.length)).length,requests:extractor.requests,retries:extractor.retries,extractionMs},target:`persi-staging:${STAGING_PROJECT_REF}`,database:{before:baseline,afterFirst,afterSecond,secondGrowthBytes:String(BigInt(afterSecond.bytes)-BigInt(afterFirst.bytes))},preserved:{mappings:`${preserved}/${beforeMappings.length}`,products:baselineProducts.length,variants:baselineVariants.length},firstPass:{durationMs:firstMs,metrics:snapshot(importer.metrics),p50Ms:percentile(sorted,.5),p95Ms:percentile(sorted,.95),slowest:profiles[0]??null,productsPerMinute:Math.round(TOTAL/(firstMs/60000)*10)/10},secondPass:{durationMs:secondMs,metrics:secondMetrics},reconciliation:{first:firstReconciliation,second:secondReconciliation},integrity:audit,quality:{gtinNull:preflight.gtin.operationalNull,gtinDuplicateGroups:preflight.gtin.duplicateGroups,gtinSourceConflicts:preflight.gtin.sourceConflicts,pim:preflight.pim,invalidPrices:preflight.invalidPrices},policies:{money:"HALF_UP exact decimal",gtin:"global_unique_id precedence; duplicate groups NULL"}};
  fs.writeFileSync(RESULT_PATH,JSON.stringify(result,null,2));console.log(JSON.stringify({run:result.run,source:result.source,database:result.database,preserved:result.preserved,firstPass:result.firstPass,secondPass:result.secondPass,reconciliation:{first:firstReconciliation,second:secondReconciliation},integrity:audit,quality:result.quality},null,2));
  const secondWrites=secondMetrics.insert+secondMetrics.update+secondMetrics.delete,integrityFailures=Object.values(audit).reduce((sum,value)=>sum+Number(value),0);if(afterSecond.products!==TOTAL||afterSecond.variants!==TOTAL||secondReconciliation.criticalDifferences||secondWrites||integrityFailures||afterSecond.inventory_movements!==0)process.exitCode=1;
}finally{await sql.end({timeout:5});}
