import { normalizeStatus, sanitizeDescription, slugify, ATTRIBUTE_RULES } from "./normalize.mjs";
import { mapSellableItems, validateMappedItems } from "./map.mjs";
import { createWriteMetrics, planSetSync, recordWrite } from "./sync.mjs";

async function mapping(tx, type, externalId) {
  const [row] = await tx`select internal_id,external_sku,status from public.external_mappings where system='woocommerce' and entity_type=${type} and external_id=${String(externalId)}`;
  return row ?? null;
}
async function saveMapping(tx, metrics, type, externalId, internalId, sku = null, sourceChangedAt = null) {
  const current = await mapping(tx, type, externalId);
  if (!current) {
    await tx`insert into public.external_mappings(system,entity_type,external_id,internal_id,external_sku,last_synced_at,source_changed_at) values('woocommerce',${type},${String(externalId)},${internalId},${sku},now(),${sourceChangedAt})`;
    recordWrite(metrics, "external_mapping", "insert");
  } else if (current.internal_id !== internalId || current.external_sku !== sku || current.status !== "active") {
    await tx`update public.external_mappings set internal_id=${internalId},external_sku=${sku},last_synced_at=now(),source_changed_at=coalesce(${sourceChangedAt},source_changed_at),status='active' where system='woocommerce' and entity_type=${type} and external_id=${String(externalId)}`;
    recordWrite(metrics, "external_mapping", "update");
  } else recordWrite(metrics, "external_mapping", "noop");
}

export class CatalogImporter {
  constructor(sql, { categories, brands, profiling = false, duplicateGtins = new Set(), freeShippingIds = new Set() }) {
    this.sql=sql; this.categories=new Map(categories.map((x)=>[x.id,x])); this.brands=new Map(brands.map((x)=>[x.id,x]));
    this.transactions=0; this.metrics=createWriteMetrics(); this.profiling=profiling; this.profiles=[];this.duplicateGtins=duplicateGtins;this.freeShippingIds=freeShippingIds;
  }
  async phase(profile,name,work){const start=performance.now();try{return await work();}finally{profile.phases[name]=(profile.phases[name]??0)+(performance.now()-start);}}
  async ensureCategory(tx, externalId, stack=new Set()) {
    const existing=await mapping(tx,"category",externalId); if(existing){const source=this.categories.get(externalId);if(source){const changed=await tx`update public.categories set name=${source.name},slug=${source.slug||slugify(source.name)},description=${sanitizeDescription(source.description)},sort_order=${source.menu_order??0},image_url=${source.image?.src??null},image_alt=${source.image?.alt??null} where id=${existing.internal_id} and (name,slug,description,sort_order,image_url,image_alt) is distinct from (${source.name},${source.slug||slugify(source.name)},${sanitizeDescription(source.description)},${source.menu_order??0},${source.image?.src??null},${source.image?.alt??null}) returning id`;recordWrite(this.metrics,"category",changed.length?"update":"noop");}return existing.internal_id;}
    if(stack.has(externalId))throw new Error("CATEGORY_CYCLE"); stack.add(externalId);
    const source=this.categories.get(externalId);if(!source)throw new Error("CATEGORY_NOT_FOUND");
    const parentId=source.parent?await this.ensureCategory(tx,source.parent,stack):null;
    const [row]=await tx`insert into public.categories(parent_id,name,slug,description,sort_order,status,published_at,image_url,image_alt) values(${parentId},${source.name},${source.slug||slugify(source.name)},${sanitizeDescription(source.description)},${source.menu_order??0},'active',now(),${source.image?.src??null},${source.image?.alt??null}) returning id`;
    recordWrite(this.metrics,"category","insert");await saveMapping(tx,this.metrics,"category",externalId,row.id);return row.id;
  }
  async ensureBrand(tx,source){
    if(!source)return null;const existing=await mapping(tx,"brand",source.id);
    const detail=this.brands.get(source.id)??source;if(existing){const changed=await tx`update public.brands set name=${detail.name},slug=${detail.slug||slugify(detail.name)},description=${sanitizeDescription(detail.description)},image_url=${detail.image?.src??null},image_alt=${detail.image?.alt??null} where id=${existing.internal_id} and (name,slug,description,image_url,image_alt) is distinct from (${detail.name},${detail.slug||slugify(detail.name)},${sanitizeDescription(detail.description)},${detail.image?.src??null},${detail.image?.alt??null}) returning id`;recordWrite(this.metrics,"brand",changed.length?"update":"noop");return existing.internal_id;}const [row]=await tx`insert into public.brands(name,slug,description,status,published_at,image_url,image_alt) values(${detail.name},${detail.slug||slugify(detail.name)},${sanitizeDescription(detail.description)},'active',now(),${detail.image?.src??null},${detail.image?.alt??null}) returning id`;
    recordWrite(this.metrics,"brand","insert");await saveMapping(tx,this.metrics,"brand",source.id,row.id);return row.id;
  }
  async ensureShared(tx){
    let [priceList]=await tx`select id from public.price_lists where code='woo-brl'`;if(!priceList){[priceList]=await tx`insert into public.price_lists(code,name,currency,channel,status) values('woo-brl','Woo snapshot BRL','BRL','storefront','active') returning id`;recordWrite(this.metrics,"price_list","insert");}else recordWrite(this.metrics,"price_list","noop");
    let [location]=await tx`select id from public.inventory_locations where code='woo-snapshot'`;if(!location){[location]=await tx`insert into public.inventory_locations(code,name,status) values('woo-snapshot','Woo migration snapshot','active') returning id`;recordWrite(this.metrics,"inventory_location","insert");}else recordWrite(this.metrics,"inventory_location","noop");
    return{priceListId:priceList.id,locationId:location.id};
  }
  async syncCategories(tx,productId,desired){
    const current=(await tx`select category_id from public.product_categories where product_id=${productId}`).map((x)=>x.category_id);const plan=planSetSync(current,desired);
    for(const id of plan.remove)await tx`delete from public.product_categories where product_id=${productId} and category_id=${id}`;
    for(const id of plan.add)await tx`insert into public.product_categories(product_id,category_id) values(${productId},${id})`;
    recordWrite(this.metrics,"product_category","delete",plan.remove.length);recordWrite(this.metrics,"product_category","insert",plan.add.length);recordWrite(this.metrics,"product_category","noop",plan.keep.length);
  }
  async syncMedia(tx,productId,images){
    const desired=[];
    for(const [index,image]of images.entries()){
      const found=await mapping(tx,"media_asset",image.id);let mediaId=found?.internal_id;const mime=image.src?.toLowerCase().endsWith(".png")?"image/png":"image/jpeg";
      if(!mediaId){const [row]=await tx`insert into public.media_assets(kind,storage_provider,storage_path,public_url,mime_type,alt_text,title) values('image','wordpress',${String(image.id)},${image.src},${mime},${image.alt||null},${image.name||null}) returning id`;mediaId=row.id;recordWrite(this.metrics,"media_asset","insert");await saveMapping(tx,this.metrics,"media_asset",image.id,mediaId);}
      else{const changed=await tx`update public.media_assets set public_url=${image.src},mime_type=${mime},alt_text=${image.alt||null},title=${image.name||null} where id=${mediaId} and (public_url,mime_type,alt_text,title) is distinct from (${image.src},${mime},${image.alt||null},${image.name||null}) returning id`;recordWrite(this.metrics,"media_asset",changed.length?"update":"noop");}
      desired.push({mediaId,role:index===0?"primary":"gallery",sortOrder:index});
    }
    const current=await tx`select id,media_asset_id,role,sort_order from public.product_media where product_id=${productId} and variant_id is null`;const key=(x)=>`${x.mediaId??x.media_asset_id}:${x.role}:${x.sortOrder??x.sort_order}`;const plan=planSetSync(current,desired,key);
    for(const row of plan.remove)await tx`delete from public.product_media where id=${row.id}`;
    for(const row of plan.add)await tx`insert into public.product_media(product_id,media_asset_id,role,sort_order) values(${productId},${row.mediaId},${row.role},${row.sortOrder})`;
    recordWrite(this.metrics,"product_media","delete",plan.remove.length);recordWrite(this.metrics,"product_media","insert",plan.add.length);recordWrite(this.metrics,"product_media","noop",plan.keep.length);
  }
  async syncPim(tx,productId,attributes){
    const desired=[];
    for(const attribute of attributes){const rule=ATTRIBUTE_RULES.get(String(attribute.slug??"").toLowerCase());if(!rule||rule.entity==="brand")continue;
      let [definition]=await tx`select id from public.attributes where code=${rule.code}`;if(!definition){[definition]=await tx`insert into public.attributes(code,name,data_type,cardinality,is_commercial,is_technical,is_filterable,status) values(${rule.code},${attribute.name},'option','multiple',true,false,true,'active') returning id`;recordWrite(this.metrics,"attribute","insert");}else recordWrite(this.metrics,"attribute","noop");
      for(const option of attribute.options??[]){const code=slugify(option).slice(0,100)||"unknown";let [value]=await tx`select id from public.attribute_values where attribute_id=${definition.id} and option_code=${code}`;if(!value){[value]=await tx`insert into public.attribute_values(attribute_id,display_value,normalized_text,option_code) values(${definition.id},${option},${option.normalize("NFKC")},${code}) returning id`;recordWrite(this.metrics,"attribute_value","insert");}else recordWrite(this.metrics,"attribute_value","noop");desired.push({attributeId:definition.id,valueId:value.id});}}
    const current=await tx`select attribute_id,attribute_value_id from public.product_attribute_values where product_id=${productId}`;const key=(x)=>`${x.attributeId??x.attribute_id}:${x.valueId??x.attribute_value_id}`;const plan=planSetSync(current,desired,key);
    for(const row of plan.remove)await tx`delete from public.product_attribute_values where product_id=${productId} and attribute_id=${row.attribute_id} and attribute_value_id=${row.attribute_value_id}`;
    for(const row of plan.add)await tx`insert into public.product_attribute_values(product_id,attribute_id,attribute_value_id) values(${productId},${row.attributeId},${row.valueId})`;
    recordWrite(this.metrics,"pim_assignment","delete",plan.remove.length);recordWrite(this.metrics,"pim_assignment","insert",plan.add.length);recordWrite(this.metrics,"pim_assignment","noop",plan.keep.length);
  }
  async syncTags(tx,productId,tags){const desired=[];for(const tag of tags??[]){let[row]=await tx`insert into public.product_tags(woo_external_id,name,slug) values(${tag.id},${tag.name},${tag.slug}) on conflict(woo_external_id) do update set name=excluded.name,slug=excluded.slug where (product_tags.name,product_tags.slug) is distinct from (excluded.name,excluded.slug) returning id`;if(!row)[row]=await tx`select id from public.product_tags where woo_external_id=${tag.id}`;desired.push(row.id);}const current=(await tx`select tag_id from public.product_tag_assignments where product_id=${productId}`).map((x)=>x.tag_id),plan=planSetSync(current,desired);for(const id of plan.remove)await tx`delete from public.product_tag_assignments where product_id=${productId} and tag_id=${id}`;for(const id of plan.add)await tx`insert into public.product_tag_assignments(product_id,tag_id) values(${productId},${id})`;recordWrite(this.metrics,"product_tag","delete",plan.remove.length);recordWrite(this.metrics,"product_tag","insert",plan.add.length);recordWrite(this.metrics,"product_tag","noop",plan.keep.length);}
  async importProduct(product,variations=[]){
    const profile={wooId:product.id,sku:product.sku,totalMs:0,phases:{}};const totalStart=performance.now();
    const items=await this.phase(profile,"normalization",async()=>mapSellableItems(product,variations,{duplicateGtins:this.duplicateGtins}));
    const conflicts=await this.phase(profile,"validation",async()=>validateMappedItems(product,items));if(conflicts.length)return{status:"conflict",conflicts};
    const result=await this.sql.begin(async(tx)=>{this.transactions+=1;const sourceChangedAt=product.date_modified_gmt?`${product.date_modified_gmt}Z`:null;
      const shared=await this.phase(profile,"shared",()=>this.ensureShared(tx));const categoryIds=[];
      await this.phase(profile,"categories",async()=>{for(const category of product.categories??[])categoryIds.push(await this.ensureCategory(tx,category.id));});
      const brandId=await this.phase(profile,"brand",()=>this.ensureBrand(tx,product.brands?.[0]));const state=normalizeStatus(product.status,product.date_created_gmt);
      const found=await mapping(tx,"product",product.id);let productId=found?.internal_id,created=false;const short=sanitizeDescription(product.short_description),description=sanitizeDescription(product.description),type=product.type==="variable"?"variable":"simple",productSlug=slugify(product.slug||product.name);
      const commercial={visibility:product.catalog_visibility??"visible",purchasable:product.purchasable===true,backorder:product.backorders_allowed===true||product.backorders==="yes"||product.backorders==="notify",manage:product.manage_stock===true,stock:product.stock_status??"outofstock",rating:String(Number(product.average_rating)||0),reviews:Number(product.rating_count)||0,featured:product.featured===true,popularity:Math.max(0,Number(product.total_sales)||0),free:this.freeShippingIds.has(product.id)};
      await this.phase(profile,"product",async()=>{if(!productId){const[row]=await tx`insert into public.products(brand_id,name,slug,short_description,description,product_type,status,published_at,archived_at,catalog_visibility,is_purchasable,allows_backorder,manage_stock,woo_stock_status,average_rating,review_count,is_featured,popularity,has_free_shipping) values(${brandId},${product.name},${productSlug},${short},${description},${type},${state.status},${state.publishedAt},${state.status==="archived"?new Date().toISOString():null},${commercial.visibility},${commercial.purchasable},${commercial.backorder},${commercial.manage},${commercial.stock},${commercial.rating},${commercial.reviews},${commercial.featured},${commercial.popularity},${commercial.free}) returning id`;productId=row.id;created=true;recordWrite(this.metrics,"product","insert");await saveMapping(tx,this.metrics,"product",product.id,productId,null,sourceChangedAt);}
      else{const archivedAt=state.status==="archived"?new Date().toISOString():null;const changed=await tx`update public.products set brand_id=${brandId},name=${product.name},slug=${productSlug},short_description=${short},description=${description},product_type=${type},status=${state.status},published_at=${state.publishedAt},archived_at=${archivedAt},catalog_visibility=${commercial.visibility},is_purchasable=${commercial.purchasable},allows_backorder=${commercial.backorder},manage_stock=${commercial.manage},woo_stock_status=${commercial.stock},average_rating=${commercial.rating},review_count=${commercial.reviews},is_featured=${commercial.featured},popularity=${commercial.popularity},has_free_shipping=${commercial.free} where id=${productId} and (brand_id,name,slug,short_description,description,product_type,status,published_at,archived_at,catalog_visibility,is_purchasable,allows_backorder,manage_stock,woo_stock_status,average_rating,review_count,is_featured,popularity,has_free_shipping) is distinct from (${brandId},${product.name},${productSlug},${short},${description},${type},${state.status},${state.publishedAt},${archivedAt},${commercial.visibility},${commercial.purchasable},${commercial.backorder},${commercial.manage},${commercial.stock},${commercial.rating},${commercial.reviews},${commercial.featured},${commercial.popularity},${commercial.free}) returning id`;recordWrite(this.metrics,"product",changed.length?"update":"noop");}});
      await this.phase(profile,"product_categories",()=>this.syncCategories(tx,productId,categoryIds));const variantIds=[];
      for(const item of items){const vm=await mapping(tx,"product_variant",item.externalId);let variantId=vm?.internal_id;const weight=item.weight||null,unit=weight?"kg":null,width=item.dimensions?.width||null,height=item.dimensions?.height||null,length=item.dimensions?.length||null,dimensionUnit=item.dimensions?"cm":null;
        await this.phase(profile,"variant",async()=>{if(!variantId){const[row]=await tx`insert into public.product_variants(product_id,sku,gtin,weight_value,weight_unit_code,width_value,height_value,length_value,dimension_unit_code,status) values(${productId},${item.sku},${item.gtin},${weight},${unit},${width},${height},${length},${dimensionUnit},${state.status}) returning id`;variantId=row.id;recordWrite(this.metrics,"variant","insert");await saveMapping(tx,this.metrics,"product_variant",item.externalId,variantId,item.sku);}
        else{const changed=await tx`update public.product_variants set sku=${item.sku},gtin=${item.gtin},weight_value=${weight},weight_unit_code=${unit},width_value=${width},height_value=${height},length_value=${length},dimension_unit_code=${dimensionUnit},status=${state.status} where id=${variantId} and (sku,gtin,weight_value,weight_unit_code,width_value,height_value,length_value,dimension_unit_code,status) is distinct from (${item.sku},${item.gtin},${weight},${unit},${width},${height},${length},${dimensionUnit},${state.status}) returning id`;recordWrite(this.metrics,"variant",changed.length?"update":"noop");}});
        variantIds.push(variantId);const regular=item.regularAmountMinor??item.saleAmountMinor;if(regular!==null){const[current]=await tx`select id from public.prices where product_variant_id=${variantId} and price_list_id=${shared.priceListId} and status='active' order by valid_from desc limit 1`;
          await this.phase(profile,"pricing",async()=>{if(!current){await tx`insert into public.prices(product_variant_id,price_list_id,list_amount_minor,sale_amount_minor,sale_valid_from,sale_valid_to,currency,status,source) values(${variantId},${shared.priceListId},${regular},${item.saleAmountMinor},${item.salePeriod.from},${item.salePeriod.to},'BRL','active','woocommerce')`;recordWrite(this.metrics,"price","insert");}
          else{const changed=await tx`update public.prices set list_amount_minor=${regular},sale_amount_minor=${item.saleAmountMinor},sale_valid_from=${item.salePeriod.from},sale_valid_to=${item.salePeriod.to},source='woocommerce',updated_at=now() where id=${current.id} and (list_amount_minor,sale_amount_minor,sale_valid_from,sale_valid_to,source) is distinct from (${regular},${item.saleAmountMinor},${item.salePeriod.from},${item.salePeriod.to},'woocommerce') returning id`;recordWrite(this.metrics,"price",changed.length?"update":"noop");}});}
        await this.phase(profile,"inventory",async()=>{const [currentInventory]=await tx`select quantity_reserved from public.inventory_levels where product_variant_id=${variantId} and inventory_location_id=${shared.locationId} for update`;if(currentInventory&&BigInt(currentInventory.quantity_reserved)>item.stockQuantity)throw Object.assign(new Error("INVENTORY_RESERVED_CONFLICT"),{permanent:true,code:"INVENTORY_RESERVED_CONFLICT"});const inventory=await tx`insert into public.inventory_levels(product_variant_id,inventory_location_id,quantity_on_hand) values(${variantId},${shared.locationId},${item.stockQuantity}) on conflict(product_variant_id,inventory_location_id) do update set quantity_on_hand=excluded.quantity_on_hand,updated_at=now() where inventory_levels.quantity_on_hand is distinct from excluded.quantity_on_hand returning (xmax=0) inserted`;
        if(!inventory.length)recordWrite(this.metrics,"inventory_level","noop");else recordWrite(this.metrics,"inventory_level",inventory[0].inserted?"insert":"update");});
      }
      await this.phase(profile,"media",()=>this.syncMedia(tx,productId,product.images??[]));await this.phase(profile,"pim",()=>this.syncPim(tx,productId,product.attributes??[]));await this.phase(profile,"tags",()=>this.syncTags(tx,productId,product.tags??[]));await this.phase(profile,"search",()=>tx`select public.refresh_catalog_search_document(${productId})`);await tx`update public.external_mappings set last_synced_at=now(),source_changed_at=coalesce(${sourceChangedAt},source_changed_at) where system='woocommerce' and entity_type='product' and external_id=${String(product.id)}`;return{status:"imported",created,productId,variantIds,categoryCount:categoryIds.length,mediaCount:product.images?.length??0};
    });
    profile.totalMs=performance.now()-totalStart;profile.phases.transactionOverhead=Math.max(0,profile.totalMs-Object.values(profile.phases).reduce((a,b)=>a+b,0));if(this.profiling)this.profiles.push(profile);return result;
  }
}
